### ISSUE TITLE
Adt Invariants verification never times out

### ISSUE THREAD

**Issue by Zyfarok** [epfl-lara/stainless#1005]
When the solver is not able to prove or disprove an ADT invariant, it never times out.
(you have to manually interrupt the verification (Ctrl+C) if you want the solver to continue its work)

Here is the simplest example I could think of :
```Scala
import stainless.collection._

object AdtInvarTimeout {
    case class LowerBoundedList(lowerBound: BigInt, list: List[BigInt]) {
        require(list.forall(x => lowerBound < x))

        def changeBound(newBound: BigInt): LowerBoundedList = {
            require(newBound < lowerBound)
            LowerBoundedList(newBound, list)
        }
    }
}
```

**Comment by vkuncak** [comment]
I can confirm this is indeed the case with `--solvers=smt-z3`, `--solvers=smt-cvc4`, `--solvers=fairz3`, `--solvers=fairz3fairz3`.
How differently do we treat `adt` invariants, @jad-hamza and @samarion ?

**Comment by jad-hamza** [comment]
Should be fixed by https://github.com/epfl-lara/stainless/pull/1006
