### ISSUE TITLE
GenC: avoid name mangling for some types

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#1007]
Similar to #921 there should be a way to prevent GenC from name mangling types.

```scala
case class MemStream(var data: Array[UInt8], var pos: Int, var limit: Int, var error: Boolean)
{
	@export
	def stream_seek(_offset: Int):Unit =
	{
		//...
	}
}
```

results in the following C code:

```c
typedef struct {
  array_uint8 data_0;
  int32_t pos_5;
  int32_t limit_0;
  bool error_0;
} MemStream_1;

static void stream_seek(MemStream_1* thiss_2, int32_t _offset_0);
```

Because we'd like to interface manually written code with the generated code, the resulting type should be called `MemStream` instead of `MemStream_1`. This is only important for types that are passed to/from `@export`-ed functions.

**Comment by jad-hamza** [comment]
Is it ok if you have to manually annotate `MemStream` as `@export`?

**Comment by deiruch** [comment]
Sure. In facts, that's the first thing I tried :)
