### ISSUE TITLE
Equality between values of different types

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#101]
I don't think we want to support equality between values of unrelated types, right? There is a warning from the scalac compiler, but that should probably be an error in our case. Currently, sometimes an exception gets thrown, or sometimes the extraction goes through.

```scala
object SI_TypeError {
  def test() = {
    false == O
  }
}
```
> Exception in thread "main" stainless.frontend.UnsupportedCodeException: Unexpected combination of types: Boolean and Int32Type

```scala
import stainless.lang._

object SI_TypeError {
  case class Test()

  def test() = {
    !(false == Test())
  }
}
```
This one doesn't produce an exception, but prints a type explanation with untyped.

```scala
import stainless.lang._

object SI_TypeError {
  case class Test()

  def test() = {
    !(false == Test())
  } holds
}
```
This one throws a type error from the VerificationChecker.

**Comment by jad-hamza** [comment]
Another kind of example that we should reject (or accept?)

```scala
import stainless.lang._

object SubtypeEquality {
  abstract class T
  case object A extends T
  
  def lemma() {
    assert(Some(A) == Some[T](A))
  }
}
```

**Comment by samarion** [comment]
All these examples are actually correctly supported by type encoding now.
We could still reject them though, WDYT?

**Comment by samarion** [comment]
Closing as this can (and should) be handled by a linter and not a verification framework.
