### ISSUE TITLE
Mutation of non-var fields is erased

### ISSUE THREAD

**Issue by yannbolliger** [epfl-lara/stainless#1014]
Currently, if a field of a case class is mutated, that is not declared as `var`, the mutation is just erased by the `AntiAliasing` phase. However, that alters the semantics of a program, so it should at least generate a warning:

```scala
 @sealed
 sealed case class A(b: Boolean)

 def set_false(var0: A): A = {
   var (a: A) @var = var0
   a.b = false
   a
 }
```

Stainless trees:
```
 Symbols before AntiAliasing
 -------------Functions-------------
 def set_false((var0: A) @pure): A = {
   var (a: A) @var = var0
   a.b = false
   a
 }
 -------------Functions-------------
 def set_false((var0: A) @pure): A = {
   var (a: A) @var = var0
   ()
   a
 }
```

**Comment by samarion** [comment]
What!? Are case classes now mutable by default?

**Comment by yannbolliger** [comment]
I might add that this is fed in through the Rust frontend (`stainless-noxt`).

**Comment by samarion** [comment]
Hmm, I guess the `getType` methods of `Assignment` and `FieldAssignment` could check that the corresponding variable / field is indeed mutable (and return `Untyped` otherwise).

**Comment by yannbolliger** [comment]
That sounds good. I can attempt a PR for this. However, it will be hard to write a test case, as it's not something that happens in Scala...

**Comment by samarion** [comment]
You can always write a unit test in which you manually construct an invalid tree.
