### ISSUE TITLE
GenC: Do not use "static" keyword for (exported) functions

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#1039]
GenC currently uses "static" for all functions in the generated .C and .H files. It should not do that. At least exported functions (those in .H and .C) should not be marked "static". "static" in C means that the functions will only be visible/usable in the current file - this means that static functions are not available for external callers.

**Comment by jad-hamza** [comment]
I ended up removing for all functions: https://github.com/epfl-lara/stainless/pull/1040, is that ok?
