### ISSUE TITLE
Make parallelism facilities part of Context

### ISSUE THREAD

**Issue by mantognini** [epfl-lara/stainless#106]
Referring to https://github.com/epfl-lara/stainless/pull/82#issuecomment-343473259:

> > I'd also like parallelism to be off when there is an active debug section, but this can be done in a different PR.
>
> Disabling it based on command line option would require a bit of change in the design, especially if we want to avoid mutable states in `MainHelpers`, namely to move `executor` & `par` to the `Context`.

**Comment by samarion** [comment]
Parallelism wasn't quite moved into `Context` but a good-enough solution was implemented in https://github.com/epfl-lara/stainless/commit/74ac842db46899312d19d8abc5a31d3e1b26d95b so I'll close this.
