### ISSUE TITLE
Bug in effect target analysis

### ISSUE THREAD

**Issue by samarion** [epfl-lara/stainless#1077]
The following case in `getTargets` isn't quite right:
https://github.com/epfl-lara/stainless/blob/8fa04b5b931d788896585e51e836cf2a715884a4/core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala#L454-L458

If `e` has no targets, we won't return any targets at all, even though `b` could contain some unrelated targets.

I think the implementation should rather be something like:
```scala
case Let(vd, e, b) =>
  val eEffects = getTargets(e, path)
  getTargets(b, path).flatMap { be =>
    if (be.receiver == vd.toVariable) eEffects.map(_ append be)
    else Set(be)
  }
```

**Comment by jad-hamza** [comment]
Thanks! Fixed in #1088
