### ISSUE TITLE
Reification of PureScala trees

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#109]
What do you think of adding some kind of macro system to Stainless, which would let us reify a given PureScala expression into a user-space AST, that could then be manipulated by some PureScala code, before being spliced back into the program?

**Library:**
```scala
package stainless
package object reflect {

  import stainless.lang._
  import stainless.annotation._
  import stainless.collection._

  @ignore
  def reify[A](expr: A): Expr = sys.error("...")

  @ignore
  def splice[A](tree: Expr): A = sys.error("...")

  sealed abstract class Type
  case object Untyped extends Type
  case class BooleanType() extends Type
  case class UnitType() extends Type
  case class TupleType(bases: Seq[Type]) extends Type
  // etc.

  sealed abstract class Expr {
    def tpe: Type
  }
  case class Variable(id: Identifier, tpe: Type) extends Expr
  case class Application(callee: Expr, args: List[Expr], tpe: Type) extends Expr
  case class Lambda(args: List[ValDef], body: Expr, tpe: Type) extends Expr
  // etc.
}
```

```scala
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.reflect._

object test {

  def simplify(e: Expr): Expr = e match { /* ... */ }

  def eval(e: Expr): Expr = e match { /* ... */ }

  def lemma1 = {
    val expr = reify { 1 + 2 }
    eval(expr) == eval(simplify(expr))
  }.holds

  def lemma2 = {
    val expr = reify { 1 + 2 }
    splice[Int](eval(expr)) == splice[Int](simplify(expr))
  }.holds

}
```

This is of course inspired by Scala's macro system, but I was thinking of making use of it with [something like this in mind]( https://medium.com/@mandubian/experimental-compiling-scala-into-closed-cartesian-categories-language-using-scalafix-rewriter-4771c6494d38) ([original paper](http://conal.net/papers/compiling-to-categories/)).

**Comment by romac** [comment]
@jad-hamza @samarion Any thoughts on that? It's very tangential to what we're trying to achieve these days and in the other issues/PRs, but I was just wondering what you guys thought of it. Nothing pressing though, just wanted to make sure it was on your radar.

**Comment by samarion** [comment]
You should sync with @redelmann who built something similar before moving on to Welder.

I haven't yet seen a good example of a proof where better support for tree manipulation would make a significant difference. @jad-hamza has found lots of tricks to make most proofs go through in the current Stainless. Maybe making these tricks available as a library would make sense.

I'd need to see a few good examples that can't be achieved by Stainless-only code to really evaluate this.

**Comment by jad-hamza** [comment]
Eventually, I imagine we would have an interface where we see all the VCs being verified. And then for those that are stuck/timing out we could invoke Welder and try various proof tactics, or prove the VC manually.

**Comment by samarion** [comment]
> Eventually, I imagine we would have an interface where we see all the VCs being verified.

+1
But for that, we need to find someone willing to put the engineering effort into integrating with an IDE...

**Comment by romac** [comment]
> I haven't yet seen a good example of a proof where better support for tree manipulation would make a significant difference.

I don't have an example in mind either at the moment. However, I see another use case for this feature: proving correct PureScala AST transformations, or even writing a provably correct nano-phase compiler for PureScala.

**Comment by romac** [comment]
Although I guess one wouldn't reification to do that, just the AST. Reification would just be a nice-to-have at that point, to avoid manually building trees by hand. So yeah, probably not worth the added complexity in the end.

**Comment by romac** [comment]
I am gonna close this is it doesn’t seem to be a worthwhile experiment, at least until we find a good use case for it. Feel free to re-open if you find one.
