### ISSUE TITLE
Equality of arguments doesn't propagate to equality of results in multiplication (and division) with smt-z3

### ISSUE THREAD

**Issue by Zyfarok** [epfl-lara/stainless#1101]
Stainless version : 0.8.0-266-gdff1b64
z3 version : 4.8.6 - 64 bit (also tested with 4.8.10 - 64 bit)

I'm proving the following code with this command :
`stainless --timeout=5 --solvers=smt-z3 --batched --cache=false --strict-arithmetic=false BitIntegerIntTest.scala`

And the following assertion times-out :  `assert(m1 == pow2(na) * ((pow2(b) - 1) * 2 + 1))`

Since this assertion is simply a rewriting of the previous assertion with `mnb` replaced with something it is equal to, it should definitely pass. It seems that equality on arguments doesn't provide equality on the result of multiplications ?
Note 1 : Everything works fine if you use BigInts instead of Ints (wrapping constants and changing return types), which is why I suspected the problem to be related to the modular arithmetic of Ints.
Note 2 : A similar problem arises with divisions.

Here is the code :
```Scala
import stainless.annotation._
import stainless.collection._
import stainless.lang._
import stainless.proof._

object BitIntegerIntTest {
    def pow2(n: BigInt): Int = {
        require(0 <= n && n < 31)
        decreases(n)
        if(n == 0) {
            1
        } else {
            2 * pow2(n-1)
        }
    } ensuring(res => 0 < res)

    def maxUnsigned(n: BigInt): Int = {
        require(0 <= n && n <= 31)
        decreases(n + 1)
        if(n < 31) {
            pow2(n) - 1
        } else {
            assert(n == 31)
            Int.MaxValue
        }
    } ensuring(res =>
        0 <= res &&
        (if (n == 0) res == 0 else {
            (res == maxUnsigned(n - 1) + pow2(n - 1)) &&
            (res == maxUnsigned(n - 1) * 2 + 1) &&
            (res == (pow2(n - 1) - 1) * 2 + 1)
        })
    )
    
    def testMaxUnsignedMult(a: BigInt, b: BigInt): Unit = {
        require(0 <= a && a < 31 && 0 < b && a + b <= 31)
        decreases(a)
        if(0 < a) {
            assert(b < 31)
            val na = a - 1
            val nb = b + 1
            val mnb = maxUnsigned(nb)
            val m1 = pow2(na) * mnb

            assert(mnb == (pow2(b) - 1) * 2 + 1)
            assert(m1 == pow2(na) * mnb)
            assert(m1 == pow2(na) * ((pow2(b) - 1) * 2 + 1))
        }
    }
}
```

**Comment by Zyfarok** [comment]
Also tested with Z3 master build from https://github.com/Z3Prover/z3

**Comment by jad-hamza** [comment]
It's a limitation from the solver, it seems to work better in "non-incremental" mode: `--solvers=no-inc:smt-z3` (tested with Z3 4.8.10).

Sometimes you can workaround these issues by writing very specific lemmas:

```scala
    @opaque @inlineOnce
    def multCongr(a: Int, b: Int, c1: Int, c2: Int): Unit = {
      require(a == b * c1)
      require(c1 == c2)

    }.ensuring(_ =>
      a == b * c2
    )

    def testMaxUnsignedMult(a: BigInt, b: BigInt): Unit = {
        require(0 <= a && a < 31 && 0 < b && a + b <= 31)
        decreases(a)
        if(0 < a) {
            assert(b < 31)
            val na = a - 1
            val nb = b + 1
            val mnb = maxUnsigned(nb)
            val m1 = pow2(na) * mnb

            assert(mnb == (pow2(b) - 1) * 2 + 1)
            assert(m1 == pow2(na) * mnb)
            multCongr(m1, pow2(na), mnb, (pow2(b) - 1) * 2 + 1)
            assert(m1 == pow2(na) * ((pow2(b) - 1) * 2 + 1))
        }
    }
```

but here it doesn't work directly for Z3 4.8.10 (the VC for the first require of `multCongr` fails, while it should be really straightforward).
Apparently the solver (Z3 4.8.10) cannot go from `m1 == pow2(na) * mnb` to (as required by the first require of `multCongr`):

```scala
val a = m1
val b = pow2(na)
val c1 = mnb
a == b * c1
```

If you add a binding like that, it works:

```scala
    def testMaxUnsignedMult(a: BigInt, b: BigInt): Unit = {
        require(0 <= a && a < 31 && 0 < b && a + b <= 31)
        decreases(a)
        if(0 < a) {
            assert(b < 31)
            val na = a - 1
            val nb = b + 1
            val mnb = maxUnsigned(nb)
            val pa = pow2(na)
            val m1 = pa * mnb

            assert(mnb == (pow2(b) - 1) * 2 + 1)
            assert(m1 == pa * mnb)
            multCongr(m1, pa, mnb, (pow2(b) - 1) * 2 + 1)
            assert(m1 == pa * ((pow2(b) - 1) * 2 + 1))
        }
    }
```

But you don't get exactly `assert(m1 == pow2(na) * ((pow2(b) - 1) * 2 + 1))`

**Comment by Zyfarok** [comment]
You're right, it seems to work with `--solvers=no-inc:smt-z3`.
(Side-note, I also just tried with `--solvers=smt-cvc4`, in which case it doesn't work neither.)

Your other solution seems to works with all of them though, so I'll use that for now. Thanks.

Should I close this ?

**Comment by jad-hamza** [comment]
Great that it works! yes I'll close
