### ISSUE TITLE
GenC: Ensuring in inlined function results in undefined variables 

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#1118]
GenC can create invalid C code, which references undefined variables. A minimal repro in Scala:
```scala
import stainless.annotation._

@export
object Blubb
{
	@export
	def a:Unit =
	{
	    b
	}

    @inline
    def b:Unit =
    {
    } ensuring (1 == 1)
}
```

results in the following C code:
```C
/* ----------------------- function definitions ----- */

void a(void) {
    void inlined_1 = res_39;
}
```

The C code references `res_39` which is undefined. The behavior appears to occur when `@inline`d functions have an `ensuring` block.

**Comment by jad-hamza** [comment]
I think this issue was fixed a few weeks ago, are you on Stainless master?

I got this in the compiled code:
```C
void a(void) {
    
}
```

**Comment by deiruch** [comment]
Yes, this was on an old branch. Happy to read that it's fixed already.
