### ISSUE TITLE
Empty tree when using --functions

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#112]
(See https://github.com/epfl-lara/stainless/pull/111)

Before verifying the VCs, the program contains an empty tree for the definition `processMsg`.
This only happens when using the option --functions=theorem.

Full example at https://gist.github.com/jad-hamza/8e77b7e2dcb432f347e2842a86ceb0fb (not fully minimized sorry).

@mantognini Can this be related to the dependency checks?

I can investigate further to see where the empty tree appears.

**Comment by mantognini** [comment]
There are 4 `processMsg` being generated, one for each overload + the abstract one (which has no body). Your intuition is correct: only the abstract one is considered to be a dependency of `theorem`... The problem is that methods are not dependencies of their class. Could you test if updating the beginning of `Registry.process` with this work?

```scala
  private def process(classes: Seq[xt.ClassDef], functions: Seq[xt.FunDef]): Option[xt.Symbols] = {
    // Compute direct dependencies and insert the new information into our dependency graph
    val clusters = computeClusters(classes)
    val invariants = computeInvariantMapping(functions)
    val methods: xt.ClassDef => Seq[Identifier] = { cd => // NEW
      functions collect {
        case fd if fd.flags contains xt.IsMethodOf(cd.id) => fd.id
      }
    }
    def computeAllDirectDependencies(cd: xt.ClassDef) =
      computeDirectDependencies(cd) ++ clusters(cd) ++ invariants(cd) ++ methods(cd) // NEW

```

**Comment by mantognini** [comment]
Or you can use the `method_deps` branch to try it out. ;-)

**Comment by jad-hamza** [comment]
Thanks for having a look! I tried with the method_deps branch, but the tree of `processMsg` is still empty (when I print the program after all the phases, in the VerificationChecker). The tree should be a pattern matching on `thiss: Behavior`, right?

```scala
def processMsg(thiss: Behavior, msg: Msg, ctx: ActorContext): Behavior = <empty tree>[Behavior]
```

**Comment by mantognini** [comment]
Yes, you're right. When I tested you code, I added `sealed` to investigate but forgot to remove it... If all class hierarchies are sealed, I think it works. You should be able to use that to workaround the issue for now, until I thing a proper fix.

**Comment by mantognini** [comment]
I've updated the `method_deps` branch. Let me know if it works for you now.

**Comment by jad-hamza** [comment]
I tried on this example, and it seems to be working, thanks!

**Comment by mantognini** [comment]
This is now superseded by #134.
