### ISSUE TITLE
Effect on if then else expression

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#1122]
Issue reported by @samarion in https://github.com/epfl-lara/stainless/pull/1116

> It seems to me that we have some more general issues with conditional effects. What would happen if we try to pass something like `if (cond) a else b` to a function invocation which has an effect on that argument? Don't we just basically drop the cond? That seems wrong to me.

Here is an example:

```scala
object EffectOnITE {

  case class A(var x: BigInt)
  def reset(a: A): Unit = { a.x = 0 }

  def f(a1: A, a2: A): Unit = {
    reset(if (true) a1 else a2)
    assert(a1.x == 0)
    assert(a2.x == 0) // should not go through
  }

}
```

**Comment by vkuncak** [comment]
Not sure what #1121 did, but this example still passes even if the assertion fails in REPL, as expected.
```scala
object EffectOnITE {
  case class A(var x: BigInt)
  def reset(a: A): Unit = { a.x = 0 }

  def f(a1: A, a2: A): Unit = {
    reset(if (true) a1 else a2)
    assert(a1.x == 0)
    assert(a2.x == 0) // should not go through
  }
  def test ={
    f(A(1), A(2))
  }
}
```

**Comment by vkuncak** [comment]
Maybe related to https://github.com/epfl-lara/stainless/issues/916

**Comment by mario-bucev** [comment]
It also ~~effects~~ affects match expression:
```scala
object EffectOnMatchExpr {

  case class A(var x: BigInt)
  def reset(a: A): Unit = { a.x = 0 }

  def f(a1: A, a2: A): Unit = {
    reset { true match {
      case true => a1
      case _ => a2
    }}
    assert(a1.x == 0)
    assert(a2.x == 0) // should not go through
  }

}
```
