### ISSUE TITLE
"Stainless terminated with an error." when using smt-z3

### ISSUE THREAD

**Issue by SimonGuilloud** [epfl-lara/stainless#1162]
I've written a project verified by stainless in this project here https://github.com/SimonGuilloud/minihol .
The two files supposed to be verified are Core.scala and Theorems.scala.
I am using this command: 
`stainless src/main/scala/Core.scala src/main/scala/Theorems.scala --vc-cache=false  --solvers=smt-z3`
Which fail with error message
```
[ Error  ] Stainless terminated with an error.
[ Error  ] Debug output is available in the file `stainless-stack-trace.txt`, you may report your issue on https://github.com/epfl-lara/stainless/issues
[ Error  ] You may use --debug=frontend to have the stack trace displayed in the output.
```
Using
`stainless src/main/scala/Core.scala src/main/scala/Theorems.scala --vc-cache=false`
instead works fine, except for some indeterminacy.

The trace file is attached
[stainless-stack-trace.txt](https://github.com/epfl-lara/stainless/files/7154168/stainless-stack-trace.txt)

**Comment by jad-hamza** [comment]
Can you try with latest Stainless and latest Z3 (4.8.12)? (the `--debug=frontend` message is outdated, it should be `--debug=stack` now)
