### ISSUE TITLE
Inlining opaque or extern functions make wrong assertions go through

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#1167]
```scala
import stainless.annotation._

object Test {
  @opaque @inlineOnce def f: Int = 0
  @opaque @inlineOnce def g: Int = 1
  def test = assert(f == g)
}
```

With PR https://github.com/epfl-lara/stainless/pull/1166, Stainless accepts this assertion, the VC which gets generated is `NoTree[Int] == NoTree[Int]` which is simplified to `true`.

I wanted to replace the `NoTree` with a `Choose` (one per function), this way this assertion would fail, but for opaque functions with an argument, `f(0) == f(1)` would still be accepted if the `Choose` is inlined.

@samarion I feel we already discussed this somewhere?

**Comment by samarion** [comment]
Hmm, I don't remember that discussion.

There's some logic in Inox which wraps chooses into functions with the right number of  arguments: [ChooseEncoder](https://github.com/epfl-lara/inox/blob/cd9632aa69e3e460add6cf3c119ffeee440e41bd/src/main/scala/inox/solvers/unrolling/ChooseEncoder.scala). Maybe you could call the encoder inside Stainless before inlining? That would fix the issue with `f(0) == f(1)`, and the more general issue of inlining functions which contain chooses.

**Comment by jad-hamza** [comment]
So we add a phase for it right before `FunctionInlining`?

**Comment by samarion** [comment]
Yeah, I would expect that to work. Otherwise, maybe you can just disallow inlining of functions which contain `Choose` or `NoTree`? It seems like @romac did something similar in the [PartialEvaluator](https://github.com/epfl-lara/stainless/blob/4e5edc08e44ea013d94f7614016f82307f4cfff5/core/src/main/scala/stainless/transformers/PartialEvaluator.scala#L80).

**Comment by jad-hamza** [comment]
I've copied `ChooseEncoder` here: https://github.com/epfl-lara/stainless/pull/1174, this seems to work well!
