### ISSUE TITLE
Ensure termination of `isSubtypeOf`

### ISSUE THREAD

**Issue by mantognini** [epfl-lara/stainless#118]
Quoting @samarion from https://github.com/epfl-lara/stainless/pull/78#issuecomment-345967833

> we need to make sure `isSubtypeOf` terminates which might not be the case depending on the type definitions within the program... I'll have to think about this a bit, but I believe that `isSubtypeOf` termination by construction is a feature we want so we can go ahead with ignoring `@unchecked` functions.

**Comment by samarion** [comment]
No longer relevant with the new type encoding.
