### ISSUE TITLE
Discussion forum for Stainless

### ISSUE THREAD

**Issue by ulugbekna** [epfl-lara/stainless#1181]
Hi, 

I was wondering whether there's a discussion forum/chat for Stainless. If not, maybe it's worth creating a Github "Discussions" for user to ask questions that are not really issues.

Thanks! 
Ulugbek

**Comment by jad-hamza** [comment]
Hi,

We have a gitter channel here: https://gitter.im/epfl-lara/stainless
It's not very active but I'll go there in case you have questions

**Comment by ulugbekna** [comment]
Thanks @jad-hamza ! :-) I managed to resolve my question, but I'll keep the link just in case
