### ISSUE TITLE
Termination checker and recursive negative types

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#120]
This is maybe a known problem, but I'm opening this issue so that we improve the reporting.
Stainless reports that this program is terminating, which leads to an inconsistency (proving `false`).

We can either forbid recursive negative types, or add support for them in the termination checker.
What do you think?

```scala
import stainless.lang._

object Inconsistency {
  sealed abstract class Code
  case class Fold(f: Code => Boolean) extends Code

  def negDiag(c: Code): Boolean = c match {
    case Fold(f) => !f(c)
  }

  def theorem() = {
    negDiag(Fold(negDiag _)) // reduces to !negDiag(Fold(negDiag _)), etc.
    assert(false)
  }
}
```

**Comment by samarion** [comment]
Indeed, I haven't gotten around to disallowing these. I'll forbid recursive negative types in the termination checker for now and we can see later if we come up with a weaker sufficient termination condition.

I ran into [this question about guarded negative recursion](https://cstheory.stackexchange.com/questions/14415/guarded-negative-occurrences-in-definition-of-inductive-types-always-bad) when considering/researching the actual condition we need to check which is an interesting read.
