### ISSUE TITLE
Consistency issue with streams

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#121]
I see two problems with this example. The first is that precondition inferences infers that the precondition of the lambda is `false`. This is a minor issue but we should probably still fix it even if we don't use the precondition inference anymore

To avoid the first issue, I add `require(true)` explicitly. The second issue (unrelated to the first I think), is that the program verifies (the following VC is reported to be valid)

```scala
[  Info  ]  - Now solving 'postcondition' VC for infiniteStream @24:14...
[ Debug  ] val x$1: SCons = SCons(() => {
[ Debug  ]   require(true)
[ Debug  ]   val x: Stream = infiniteStream
[ Debug  ]   assert(false)
[ Debug  ]   x
[ Debug  ] })
[ Debug  ] false
```

```scala
object Inconsistency2 {
  sealed abstract class Stream
  case class SCons(s: () => Stream) extends Stream

  def infiniteStream(): Stream = {
    SCons(() => {
      require(true) // precondition inference infers require(false) here
      val x = infiniteStream()
      assert(false)
      x
    })
  } ensuring(_ => false)
}
```

**Comment by jad-hamza** [comment]
This should perhaps be a different issue, but since it's also related to Streams, I'm putting it there. The program is validated as terminating while it shouldn't. This is an example taken from the Cpdt book http://adam.chlipala.net/cpdt/html/Coinductive.html.

```scala
object Termination {
  abstract class Stream
  case class SCons(head: BigInt, tail: () => Stream) extends Stream

  def tail(s: Stream): Stream = s match {
    case SCons(_, tail) => tail()
  }

  def zeros(): Stream = tail(SCons(0, zeros _))

  val x = zeros() // reduces to tail(SCons(0, zeros _)), i.e. zeros() (loop)
}
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/f041d2db6b5c9bdb64b176506c9471724c1939d7

**Comment by jad-hamza** [comment]
@samarion Thanks! What were the problems here for Inconsistency2 and Termination?

For Inconsistency2, why was the postcondition check suceeding before the fix?

For Termination, I guess it was due to a missing check for the occurrence "zeros _" (because that lambda may be invoked during the lifetime of zeros())?

**Comment by samarion** [comment]
For Inconcistency2, there was an invalid lifting of `assume` in lambda bodies, so `infiniteStream` was being transformed to
```scala
def infiniteStream(): Stream = {
  assume(false)
  SCons(() => {
    require(true) // precondition inference infers require(false) here
    val x = infiniteStream()
    x
  })
} ensuring(_ => false)
```

For Termination, the CFA analysis was doing various things not quite right IIRC.
