### ISSUE TITLE
ResolveException: Error downloading default:cafebabe

### ISSUE THREAD

**Issue by mbovel** [epfl-lara/stainless#1217]
Hi,

Sorry for the basic question, but I can't find why I can't build Stainless anymore:

```
$ git clone git@github.com:epfl-lara/stainless.git sl
...
$ cd sl
cs java --version                                    
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
$ cs java -version 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
$ sbt --version
sbt version in this project: 	1.5.6
sbt script version: 1.5.7
$ sbt universal:stage            
[info] welcome to sbt 1.5.6 (AdoptOpenJDK Java 1.8.0_292)
...
[error] sbt.librarymanagement.ResolveException: Error downloading default:cafebabe_2.13:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/mbovel/.ivy2/localdefault/cafebabe_2.13/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/default/cafebabe_2.13/0.1.0-SNAPSHOT/cafebabe_2.13-0.1.0-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/service/local/repositories/releases/content/default/cafebabe_2.13/0.1.0-SNAPSHOT/cafebabe_2.13-0.1.0-SNAPSHOT.pom
[error]   not found: http://logicrunch.research.it.uu.se/maven/default/cafebabe_2.13/0.1.0-SNAPSHOT/cafebabe_2.13-0.1.0-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/default/cafebabe_2.13/0.1.0-SNAPSHOT/cafebabe_2.13-0.1.0-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/default/cafebabe_2.13/0.1.0-SNAPSHOT/cafebabe_2.13-0.1.0-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
```

It seems like SBT tries to fetch [cafebabe](https://github.com/epfl-lara/cafebabe) from the wrong place.

I read that similar problems can be caused by [using an inadequate Java version](https://stackoverflow.com/a/61703971) or because of a [Scala version mismatch between the project and its dependency](https://stackoverflow.com/a/42203814) but these don't seem to be the case here (I am using Java 1.8 and both this project and cafebabe have `scalaVersion := "2.13.6"`).

Any idea what could be wrong?

**Comment by mario-bucev** [comment]
Hello!
It is strange that SBT is interested in downloading the `0.1.0-SNAPSHOT` version of `cafebabe`, even though Stainless depends on a [commit hash](https://github.com/epfl-lara/stainless/blob/087a85e4437e2e156689d7a161c4c437a0052891/build.sbt#L237)
When running SBT for the first time on the repo, it should print a message such as:
```
Cloning in '~/.sbt/1.0/staging/7beae08b0c0069536367/cafebabe'...
```
I have tried to reproduce the issue by removing all cached `cafebabe` instances and on a fresh clone but without success.
I'll investigate the issue further and let you know if I find anything.

**Comment by mbovel** [comment]
Got it working by removing my `~/.sbt` folder! Not sure what the problem was.

In my old `.sbt` directory, `1.0/staging/7beae08b0c0069536367/cafebabe` just contains `.git` and `target` directories, and `git` commands yield `not a git repository`.

In the new `.sbt` directory, `1.0/staging/7beae08b0c0069536367/cafebabe` is a valid clone of `https://github.com/epfl-lara/cafebabe.git`. I can now run `sbt universal:stage` and build Stainless successfully.

**Comment by mario-bucev** [comment]
Great! Glad you got it working; this kind of issue is a good call for switching off from using git hashes dependencies :p
