### ISSUE TITLE
Mutually recursive calls not detected as infinite loop

### ISSUE THREAD

**Issue by timotheeandres** [epfl-lara/stainless#1223]
In our project, a function definition calls a lemma to prove that it is consistent. However, this lemma calls the function back to compute some result, but Stainless does not complain about it.

The call to the lemma is located [here, in `Ordinal.mult`](https://gitlab.epfl.ch/bernet/transfinite-lists-for-stainless/-/blob/master/implementation/ordinal.scala#L179). This lemma [calls the star operator](https://gitlab.epfl.ch/bernet/transfinite-lists-for-stainless/-/blob/master/lemmas/Mult.scala#L19) of `Ordinal`, which [itself calls `Ordinal.mult`](https://gitlab.epfl.ch/bernet/transfinite-lists-for-stainless/-/blob/master/implementation/ordinal.scala#L45).

When running Stainless with the command `stainless --functions=mult,tailSmallerThanOmegaExp --solvers=smt-z3 implementation/* lemmas/*`, all tests pass, even if the measure of the arguments `a` and `b` do not decrease between calls.

**Comment by mario-bucev** [comment]
It was due to [`tailSmallerThanOmegaExp` being annotated as `@inlineOnce`](https://gitlab.epfl.ch/bernet/transfinite-lists-for-stainless/-/blob/master/lemmas/Mult.scala#L16-22).
This was fixed by #1338.
Now Stainless sees the mutually recursive call (for better or worse...) and is sadly not able to prove it within 30s:
```
[Warning ] Interrupted...
[Warning ]  - Result for 'measure decreases' VC for mult$0 @45:29:
[Warning ] alpha$28.isInstanceOf[Nat$2] && alpha$28.n$17 == BigInt("0") || beta$26.isInstanceOf[Nat$2] && beta$26.n$17 == BigInt("0") || alpha$28.isInstanceOf[Nat$2] || beta$26.isInstanceOf[Nat$2] || {
[Warning ]   val newExp$1: Ordinal$0 = add$0(alpha$28.exp$3, beta$26.exp$3)
[Warning ]   val newTail$1: Ordinal$0 = mult$0(alpha$28, beta$26.tail$9)
[Warning ]   val b$8799: Ordinal$0 = beta$26
[Warning ]   !b$8799.isInstanceOf[Transfinite$0] || !(Nat$2(BigInt("0")) < alpha$28) || length$1(b$8799) < length$1(beta$26)
[Warning ] }
[Warning ] implementation/ordinal.scala:45:29:  => CANCELLED
               def * (that: Ordinal) = Ordinal.mult(this, that)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
```
