### ISSUE TITLE
Exception/Reporting problem with Any

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#124]
I obtain an exception with the following file

> Caused by: inox.ast.Definitions$ADTLookupException: Lookup failed for adt with symbol `stainless.lang.Option$0`

```scala
object Reporting {
  case class Machine(f: Any => Boolean)

  def negateDiagonal(x: Any): Boolean = x match {
    case Machine(f) => !f(x)
    case _ => true
  }
}
```

**Comment by samarion** [comment]
The extraction problem has now been fixed (though the termination issue still remains). Closing since we have  https://github.com/epfl-lara/stainless/issues/123 for termination with `Any`.
