### ISSUE TITLE
Inner functions capturing variables of mutable type too conservative

### ISSUE THREAD

**Issue by mario-bucev** [epfl-lara/stainless#1268]
The following snippet is rejected though it should not:
```scala
object VarVal {
  case class Box(var value: Int)

  def outer: Unit = {
    val box = Box(123)
    assert(box.value == 123) // ok

    def inner: Unit = {
      assert(box.value == 123) // reported as invalid, though it is not
    }
  }
}
```

In the general case, such assertion may not always hold (as `box.value` can be changed), but here we know for sure it is not mutated.
If we look at the `AntiAliasing` (who would have thought! :p) transformation output, we can see the reason:
```scala
def outer: Unit = {
  var box = Box(123)
  assert(box.value == 123)
  def inner: Unit = {
    assert(box.value == 123)
  }
}
```
Here `box` is `var`-bound to account for possible mutation of `value`, which triggers `ImperativeCodeElimination` to add a `box: Box` parameter to `inner`.

**Comment by samarion** [comment]
I don't think this is too conservative. Correctly determining that the assertion should hold would require cross-function analysis.
Imagine the following example:
```scala
object VarVal {
  case class Box(var value: Int)

  def outer: Unit = {
    val box = Box(123)
    assert(box.value == 123) // ok

    def inner: Unit = {
      assert(box.value == 123)
    }

    inner() // valid
    box.value = 124
    inner() // invalid
  }
}
```

To correctly check the assertion we would need to capture the call-sites of `inner` during encoding which breaks modularity.

**Comment by samarion** [comment]
Oh I see. That makes sense to me. I guess you can use the existing effects checking mechanisms to detect whether a locale is mutated.
