### ISSUE TITLE
Inconsistency between inlining and equality of lambdas

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#127]
[This program](
https://gist.github.com/jad-hamza/5fc46cbfd6b9367c52095f99facbd2ed) fully verifies (including the assertion false). There seem to be an inconsistency between the way we do inlining, and the way we interpret equality between lambdas. Below the theorem are some facts that verify but that perhaps should not (marked with `// ?`). Over the whole program, what are the contracts that should verify and the ones that are bugs?

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/ac7cce84e9c9e4afd43942ff86f659330dbc593a and https://github.com/epfl-lara/inox/commit/d207633a2c5cee5a29d223875e5b8b49a0853932.

The issue was with variable substitutions changing the structure of a lambda by introducing more precise types for the variable replacements. So the assertion marked with `// ?` in `theorem` should not hold.

About `strangeFacts`, I think you should have (if the assertions are considered independently)
- false
- false
- false
- true
- false

**Comment by jad-hamza** [comment]
Awesome! Thanks

**Comment by jad-hamza** [comment]
@samarion I noticed a difference in behavior for equality when `val`'s are local (`c` and `d`) versus when they are defined globally (`a` and `b`). Is this expected?

```scala
import stainless.lang._

object Equality {
  sealed abstract class Nat
  case class Zero() extends Nat 
  case class Succ(n: Nat) extends Nat

  def plus(a: Nat, b: Nat): Nat = a match {
    case Zero() => b
    case Succ(a2) => Succ(plus(a2,b))
  }

  val z = Zero()
  val a = plus(z,z)
  val b = plus(z,z)

  def th() = {
    assert(a == b)
    assert((() => a) != (() => b))  // ?
    val c = plus(z,z)
    val d = plus(z,z)
    assert((() => c) == (() => d))
  }
}
```

**Comment by samarion** [comment]
Yes, this is expected as the global vals `a` and `b` are extracted as (potentially) impure functions (depending on the termination of `plus`). So they are not lifted as closures in `() => a` and `() => b`.

Once we move to total functions, we could lift them in certain cases but not always (see your inconsistent stream example in https://github.com/epfl-lara/stainless/issues/121). It may be useful to add a transformation that injects global variables as let definitions within functions to avoid this sort of issue...

**Comment by jad-hamza** [comment]
I see, thanks!
Is there an expression e not involving a such that () => a is equal to e? (where a is the global variable above)

**Comment by samarion** [comment]
Well, you could use `@inline` to get one but otherwise no, I don't think so.
