### ISSUE TITLE
Invalid counter-example in presence of lambda

### ISSUE THREAD

**Issue by mario-bucev** [epfl-lara/stainless#1350]
(Originally discovered by students taking the FV course)

The following snippet produces an invalid counter-example:
```scala
import stainless.collection._
import stainless.lang._
import stainless.annotation._

object NormalizeStructure {
  def test(l: List[BigInt], c: BigInt) = {
    require(l.nonEmpty)
    require(l.forall(i => i == l.head || l.head == i))
    assert(l.forall(i => i == l.head || l.head == i)) // "invalid"
  }
}
```
If we pass `--check-models`, we get the following error:
```
[Warning ] - Model leads to evaluation error: No value for variable i$32 in mapping Map(ValDef(l$36, List$1[BigInt], List()) -> Cons$0[BigInt](BigInt("3"), Cons$0[BigInt](BigInt("4"), Nil$0[BigInt]())), ValDef(x$112, BigInt, List()) -> BigInt("3"))
[ Error  ] Something went wrong. The model should have been valid, yet we got this:
[ Error  ]   l$36: List$1[BigInt] -> Cons$0[BigInt](BigInt("3"), Cons$0[BigInt](BigInt("4"), Nil$0[BigInt]()))
[ Error  ] for formula !(!nonEmpty$2[BigInt](l$36) || !forall$2[BigInt](l$36, (i$26: BigInt) => i$26 == head$1[BigInt](l$36) || head$1[BigInt](l$36) == i$26) || forall$2[BigInt](l$36, (i$27: BigInt) => i$27 == head$1[BigInt](l$36) || head$1[BigInt](l$36) == i$27))
```

When looking at [`normalizeStructure`](https://github.com/epfl-lara/inox/blob/66a2241a95fa3cb7b4d01bbdcd63faf062a61403/src/main/scala/inox/ast/SymbolOps.scala#L304), we are given this:
* Expression to normalize: `i$30 == head$1[BigInt](l$36) || head$1[BigInt](l$36) == i$30`
* Arguments: `List(ValDef(i$30, BigInt, List()))`

and yield:
* New expression: `x$111 == x$112 || x$113 == x$111`
* Bindings: `List(ValDef(x$111, BigInt, List()))`
* Dependencies: `List((x$112,head$1[BigInt](l$36),List()), (x$113,head$1[BigInt](l$36),List(i$30 ≠ head$1[BigInt](l$36))))`
In particular, the condition for `x$113` in the dependencies (`i$30 ≠ head$1[BigInt](l$36)`) did not have `i$30` substituted by `x$111`.

**Comment by samarion** [comment]
I'm not entirely sure but these lines look suspicious: https://github.com/epfl-lara/inox/blob/66a2241a95fa3cb7b4d01bbdcd63faf062a61403/src/main/scala/inox/ast/SymbolOps.scala#L395-L400

I think we should rather be checking path variables against `vs` instead of `tvs` since the path isn't transformed at this point.

**Comment by mario-bucev** [comment]
Thank you for the insights! I'll experiment with this change :)

**Comment by samarion** [comment]
Hmm, yes I believe replacing `isAlwaysPure` with `isPure` should be ok.

However, I noticed that our function purity check might not be conservative enough in the presence of dependent types:
https://github.com/epfl-lara/inox/blob/66a2241a95fa3cb7b4d01bbdcd63faf062a61403/src/main/scala/inox/transformers/SimplifierWithPC.scala#L58-L70

A couple changes we should include:
1. check that all function argument types are non-empty using `hasInstance(vd.tpe) == Some(true)`,
1. bind the function parameters in the path using `withBound` on the `initEnv`.

**Comment by mario-bucev** [comment]
Wouldn't have thought of checking `isPureFunction`, thank you :)
I've applied these changes in PR https://github.com/epfl-lara/inox/pull/192
Slight tweak from the suggestion: since `path.bound` has transformed variables and `path.condition` refers to the "old" (untransformed variables), and that we also need to check that `path.condition` does not contain bound variable from the path, the fix in the PR substitutes the old variables with the new ones with `varSubst`.

**Comment by samarion** [comment]
Are you sure `path.bound` contains transformed variables? It seems to me only untransformed variables are added to the path.

Regardless, applying `varSubst` SGTM. You could maybe adapt the if-expression to avoid returning true (which is always a bit weird):
```scala
val condVars = path.freeVariables.map(v => varSubst.getOrElse(v, v))
(tvs & allBoundVars).isEmpty && (unconditional || (condVars & allBoundVars).isEmpty)
```

**Comment by mario-bucev** [comment]
Regarding `path.bound`, if I'm not mistaken, the only place where we add bound variables is in the [last case with a non-liftable `Let`](https://github.com/epfl-lara/inox/blob/87138ad47eb2b155277dcaf5fd352e515de270ec/src/main/scala/inox/ast/SymbolOps.scala#L526) through the [default implementation](https://github.com/epfl-lara/inox/blob/87138ad47eb2b155277dcaf5fd352e515de270ec/src/main/scala/inox/transformers/TransformerWithPC.scala#L11-L12).
The reconstructed `let` has its bound variable transformed.
I've also observed that through printing (very professional...) but I may miss something!

In the meantime, I'll apply your suggestion for the if-expression, it's concise :)

**Comment by samarion** [comment]
> The reconstructed let has its bound variable transformed.

Oh I see, that's pretty yucky... 

It would be nice to clean that up at some point to make sure we don't end up with broken path conditions, but I guess it's not too important at this point.
