### ISSUE TITLE
Measures inference: information message

### ISSUE THREAD

**Issue by samuelchassot** [epfl-lara/stainless#1359]
I think it would be good to print a message in the CLI while infering the measures. It could indeed be quite a long task for some project, and, for now, nothing is printed so one could think Stainless froze.

**Comment by mario-bucev** [comment]
The option `--debug=measure-inference` prints this information, but it should perhaps be default.

**Comment by samuelchassot** [comment]
Yes, I think it would be better to show that by default.
I just tried and maybe it could be even better to show this information inline (like it is done for the VCs) rather than one line per measure. And keep this layout for the debug version.

**Comment by mario-bucev** [comment]
Yes, this is a good idea!
