### ISSUE TITLE
Use of choose not reported, issued warnings not summarized

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#1366]
Consider the file [frontends/benchmarks/verification/false-valid/MakeFalse.scala](https://github.com/epfl-lara/stainless/blob/main/frontends/benchmarks/verification/false-valid/MakeFalse.scala) 

This code uses `choose`, which we know has soundness issues, and a warning is issued, but there is no summary of `choose injection` since (technically correct; choose was given explicitly, but still funny it is not documented in the summary). Maybe we should indicate when warnings were issued in the summary line?

**Comment by vkuncak** [comment]
Insteod merely
```
Verification pipeline summary:
  cache, nativez3
```
it would be better to have:
```
Verification pipeline summary:
  warnings, cache, nativez3
```

**Comment by mario-bucev** [comment]
Should we also report library-side uses of `choose`?
