### ISSUE TITLE
Invalid counter example when using map with a function with preconditions

### ISSUE THREAD

**Issue by pgimalac** [epfl-lara/stainless#1370]
Hello,

When I run stainless on the following code, it generates an invalid counter example on the use of `f` in `map`:
```scala
def f(e: BigInt): BigInt = {
  require(e >= 0)
  e + 1
}

def g(o: Option[BigInt]): Boolean = {
  require(o.forall(_ >= 0))
  o.map(f)
  true
}.holds
```

```
Found counter-example:
  o: Option[BigInt] -> None[BigInt]()
  e: BigInt         -> BigInt("-1")
```

`None[BigInt]()` is a valid parameter for `g`, but then `f` would never be applied (and in particular not on `-1` which doesn't satisfy the prerequisite of `g`). It seems like Stainless doesn't understand that the parameter of `map` is only applied to the value inside the `Option` (and not applied at all if it's `None()`).

The same kind of issue arises with `flatMap` for example, or using `List` instead of `Option`.

I thought it was the same issue as https://github.com/epfl-lara/stainless/issues/1350, but I tried building the main branch of stainless (post merge of https://github.com/epfl-lara/stainless/pull/1364) and the resulting binary still produces the error above.

Thanks.

**Comment by mario-bucev** [comment]
Thanks for the ticket! Stainless lost its sobriety:
```
stainless-dotty i1370.scala --check-models --debug=full-vc,verification
[ Debug  ] Generating VCs for functions: f$37, g$1
[ Debug  ] Finished generating VCs
[  Info  ] Starting verification...
[  Info  ] Verified: 0 / 1
[ Debug  ]  - Checking cache: 'precond. (call f$37(x$99))' VC for g$1 @11:11...
[ Debug  ] Cache miss: 'precond. (call f$37(x$99))' VC for g$1 @11:11...
[ Debug  ]  - Now solving 'precond. (call f$37(x$99))' VC for g$1 @11:11...
[ Debug  ] 
[ Debug  ]  - Original VC:
[ Debug  ]    forall$0[BigInt](o$1, (_$1$11: BigInt) => _$1$11 >= BigInt("0")) ==> {
[ Debug  ]      val thiss$8: Option$0[BigInt] = o$1
[ Debug  ]      val e$6: BigInt = x$99
[ Debug  ]      e$6 >= BigInt("0")
[ Debug  ]    }
[ Debug  ] 
[ Debug  ]  - Simplified VC:
[ Debug  ]    !forall$0[BigInt](o$1, (_$1$11: BigInt) => _$1$11 >= BigInt("0")) || x$99 >= BigInt("0")
[ Debug  ] 
```
It's not generating a correct VC, `x$99 >= BigInt("0")` escaped the scope of the lambda. Will see if I can do something.

**Comment by samarion** [comment]
This is expected. Type-checking inside lambda bodies is modular, _i.e._ Stainless doesn't try to generate the potential inputs to lambdas when checking assertions within. (I believe it would be possible to transform the VCs to generate such non-modular counter-examples, but this wouldn't really be compatible with the dependent type-checking algorithm.)

I guess the "right" way to fix this would be to have syntactic-level support for dependent types in Stainless, and then you could write the function as:
```scala
def g(o: Option[{x: BigInt | x >= 0}]): Boolean = {
  o.map(f)
  true
}.holds
```

**Comment by mario-bucev** [comment]
Aaah I'm the one not sober, not Stainless!

**Comment by vkuncak** [comment]
For now, when working with higer-order functions, you should aim to make them total and not have require clauses.
If your function works without precondition, you can make the postcondition conditional, replacing it with
```
!pre || post
```
```scala
import stainless.lang.*
object Test: 
  def f(e: BigInt): BigInt = {
    e + 1
  } ensuring(res => !(e >= 0) || res >= 0)

  def g(o: Option[BigInt]): Option[BigInt] = {
    require(o.forall(_ >= 0))
    o.map(f)
  } ensuring(res => res.forall(_ >= 0))

end Test
```
If, in addition, some parts were to fail due to built-in preconditions or runtime preconditions, then you can do an if condition or an early return (this was not needed in the example above).

**Comment by pgimalac** [comment]
Oh ok I see !

That's an interesting workaround thank you !
