### ISSUE TITLE
Take a parameter which verifies a condition for all variables

### ISSUE THREAD

**Issue by pgimalac** [epfl-lara/stainless#1374]
Hello,

I'm wondering if Stainless can express the pre-condition of receiving as a parameter an associative function ?

I can prove that a given function is associative, but I don't know if there's a syntax to say that it should be the case for a parameter ?

Something like that maybe ?
```scala
def isAssociative[T](f: (T, T) => T)(a: T, b: T, c: T): Boolean = {
  f(f(a, b), c) == f(a, f(b, c))
}

def h[T](f: (T, T) => T, zero: T, elems: List[T]): Boolean = {
  require(isAssociative(f).holdsForall)
  elems.foldLeft(zero)(f) == elems.foldRight(zero)(f)
}.holds
```

Thanks.

**Comment by mario-bucev** [comment]
Hello!
There is no dedicated syntax for describing that a function is associative.
However, one may express this property using the `forall` quantifier available in `stainless.lang`:
```scala
import stainless.lang._

def isAssociative[A](f: (A,A) => A): Boolean = {
  forall((x: A, y: A, z: A) => f(f(x, y), z) == f(x, f(y, z)))
}

def h[T](f: (T, T) => T, zero: T, elems: List[T]): Boolean = {
  require(isAssociative(f))
  elems.foldLeft(zero)(f) == elems.foldRight(zero)(f)
}.holds

```

**Comment by pgimalac** [comment]
This is exactly what I was looking for, thanks a lot !
My use case was more general than just an associative function anyway :)

PS: the `h` function is actually false and I didn't even realize it (we need zero being a neutral element for `f` too, or `f` being commutative I guess), thanks Stainless which figured it out directly ^^
