### ISSUE TITLE
Undefined variables in preconditions

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#141]
(Related to #140)

```scala
import stainless.lang._

object AssertionFailed {
  def isForall(b: Boolean): (Boolean => Boolean) => Boolean = {
    (p: Boolean => Boolean) => b == forall(p)
  }
}
```

> [Internal] java.util.concurrent.ExecutionException: java.lang.AssertionError: assertion failed
> [Internal] Please inform the authors of Inox about this message

**Comment by mantognini** [comment]
FYI the crash happens in `inox.ast.Paths.Path.withBound` when inserting `ValDef(x$57, Boolean, Set())` into 

```
this.elements := List(OpenBound(ValDef(p, (Boolean) => Boolean, Set())), 
                      Condition(p.pre(x$57)))
```

according to my debugger. The `x$57` comes from `stainless.transformers.TransformerWithPC.rec` at `case _ => super.rec(e, env)` where 

```
e   := ∀x$57: Boolean. p(x$57)
env := p.pre(x$57) && true
```

It seems very similar to what I've described here: https://github.com/epfl-lara/stainless/pull/89#issuecomment-337625881.

**Comment by mantognini** [comment]
Here's another example that trigger probably the same bug under `--check-models`:

```scala
import stainless.lang._
import stainless.collection._

case class Lang[T](f: List[T] => Boolean) {
  def concat(that: Lang[T]): Lang[T] = {
    Lang[T](l => !forall( (i: BigInt) => !(
      i <= l.size &&
      i >= 0 &&
      this.contains(l.take(i)) &&
      that.contains(l.drop(i))
    )))
  }

  def concatTest():Boolean = {
    (Lang[Int](a => (a == List[Int](3))) concat Lang[Int](a => (a == List[Int](5))) ).contains(List[Int](5,3))
  }.holds


  def contains(word: List[T]): Boolean = f(word)
}
```

**Comment by mantognini** [comment]
I encountered the same thing (probably) while investigating #150 (although the evalutator bug is probably unrelated). Here is the program in question:

```scala

object LambdaMini {

  sealed abstract class Value
  case class IntegerValue(c: Int) extends Value
  case class FunctionValue(f: Value => Value) extends Value

  // ACK: missing cases
  def lift(op: (Int, Int) => Int): Value = FunctionValue((v1: Value) => v1 match {
    case IntegerValue(c1) => FunctionValue((v2: Value) => v2 match {
      case IntegerValue(c2) => IntegerValue(op(c1, c2))
    })
  })

  // minimized eval
  def FIXME = {
    lift(_ * _) match {
      case FunctionValue(f) => f(IntegerValue(3)) match {
        case FunctionValue(g) => g(IntegerValue(8))
      }
    }
  }

}
```

The trace is big, so see the attached file. It was generated by running `stainless LambdaMini.scala --functions=FIXME --verification`.
[crashlog.txt](https://github.com/epfl-lara/stainless/files/1572427/crashlog.txt)

**Comment by mantognini** [comment]
As mentioned in #150, the preconditions seems to be incorrectly generated:

```
[ Debug  ] Calling lift: typed def lift[]'s full body:
[ Debug  ] require(v1.isInstanceOf[IntegerValue] ==> {
[ Debug  ]   val c1: Int = v1.asInstanceOf[IntegerValue].c
[ Debug  ]   v2.isInstanceOf[IntegerValue] ==> {
[ Debug  ]     val c2: Int = v2.asInstanceOf[IntegerValue].c
[ Debug  ]     op.pre(c1, c2)
[ Debug  ]   }
[ Debug  ] })
[ Debug  ] FunctionValue((v1: Value) => {
[ Debug  ]   require(true)
[ Debug  ]   v1 match {
[ Debug  ]     case IntegerValue(c1) =>
[ Debug  ]       FunctionValue((v2: Value) => {
[ Debug  ]         require(v2.isInstanceOf[IntegerValue] ==> {
[ Debug  ]           val c2: Int = v2.asInstanceOf[IntegerValue].c
[ Debug  ]           op.pre(c1, c2)
[ Debug  ]         })
[ Debug  ]         v2 match {
[ Debug  ]           case IntegerValue(c2) =>
[ Debug  ]             IntegerValue(op(c1, c2))
[ Debug  ]         }
[ Debug  ]       })
[ Debug  ]   }
[ Debug  ] })
```

However, I'm not sure how they should actually look like. @samarion Is there a reason why (most) `require` are lifted from lambda to the outer function? Or could we have instead the following `lift` body?

```scala
FunctionValue((v1: Value) => {
  require(v1.isInstanceOf[IntegerValue])
  v1 match {
    case IntegerValue(c1) =>
      FunctionValue((v2: Value) => {
        require(v2.isInstanceOf[IntegerValue] ==> {
          val c2: Int = v2.asInstanceOf[IntegerValue].c
          op.pre(c1, c2)
        })
        v2 match {
          case IntegerValue(c2) =>
            IntegerValue(op(c1, c2))
        }
      })
  }
})
```

Or what is the recipe to generate the correct preconditions at each level (outer functions, nested lambda, forall, ...)?

**Comment by samarion** [comment]
The precondition inference transformer tries to find out which precondition on the outer function will enables all the higher-order contracts to be checked. So the behavior of lifting requirements to the outer function is correct, it's just missing a `forall v1,v2` in this case.

The issue seems to be in the free variables computation here
https://github.com/epfl-lara/stainless/blob/cd571cd904827bfe6de410282f23eb5421e69beb/core/src/main/scala/stainless/extraction/PreconditionInference.scala#L406-L408
The set of free variables in a path has changed since adding the `OpenBound` in Inox and probably led to this bug (which unfortunately wasn't caught by our regressions).

The fix should look something like:
```scala
val freeVars = path.bindings.foldRight(args.flatMap(variablesOf).toSet) {
  case ((vd, e), vars) => vars - vd.toVariable ++ variablesOf(e)
} -- fd.params.map(_.toVariable)
```

**Comment by samarion** [comment]
However, as @jad-hamza mentioned in his e-mail, spending too much time on this issue probably doesn't make much sense if we're going to move to a user-provided explicit definition of total and partial functions.

**Comment by mantognini** [comment]
Thanks @samarion for the patch. It seems to make things better: LambdaMini evaluation works.

For reference, with the patch, `lift`'s body is transformed into this:

```scala
require(∀x$57: Int, x$58: Int. op.pre(x$57, x$58))
FunctionValue((v1: Value) => {
  require(true)
  v1 match {
    case IntegerValue(c1) =>
      FunctionValue((v2: Value) => {
        require(v2.isInstanceOf[IntegerValue] ==> {
          val c2: Int = v2.asInstanceOf[IntegerValue].c
          op.pre(c1, c2)
        })
        v2 match {
          case IntegerValue(c2) =>
            IntegerValue(op(c1, c2))
        }
      })
  }
})
```

I guess the innermost `op.pre(c1, c2)` precondition could be removed given the outermost precondition, but this is a detail probably.

But it's not yet perfect. For example, if I rewrite `lift` as follows, the precondition of `op2` (incorrectly) contains a reference to `v1`.

```scala
  def lift(op1: (Int, Int) => Int): Value = FunctionValue(v1 => v1 match {
    case IntegerValue(c1) =>
      def op2(y: Int): Int = op1(c1, y)
      lift2(op2)
  })

  def lift2(op2: Int => Int): Value = FunctionValue(v2 => v2 match {
    case IntegerValue(c2) => IntegerValue(op2(c2))
  })
```

```scala
[info] [Internal] Error: Not well formed definition @derived(lift)
[info] [Internal] def op2(y: Int, op1: (Int, Int) => Int): Int = {
[info] [Internal]   require(∀x$57: Int, x$58: Int. op1.pre(x$57, x$58) && v1.isInstanceOf[IntegerValue] && {
[info] [Internal]     val c1: Int = v1.asInstanceOf[IntegerValue].c
[info] [Internal]     true
[info] [Internal]   })
[info] [Internal]   val c1: Int = v1.asInstanceOf[IntegerValue].c
[info] [Internal]   op1(c1, y)
[info] [Internal] }
[info] [Internal]       because Unknown variables: v1$1, v1$1, v1$1. 
```

**Comment by samarion** [comment]
This looks like an issue with `FunctionClosure`. The body of `op2` is not well defined regardless of the inferred precondition.

I'd say the part of the line that was commented here
https://github.com/epfl-lara/stainless/blob/cd571cd904827bfe6de410282f23eb5421e69beb/core/src/main/scala/stainless/extraction/innerfuns/FunctionClosure.scala#L102-L103
should be uncomented.

**Comment by mantognini** [comment]
Unfortunately this doesn't help. But as you said the problem is different so I'll open another issue in order to keep the discussions separate.

**Comment by samarion** [comment]
Fixed between https://github.com/epfl-lara/stainless/commit/a7e2490bcd324e22c2b65e381909c79852138510 and https://github.com/epfl-lara/stainless/commit/a7b0a571783c5494059cdb49c4ff5a23c75a0c33
