### ISSUE TITLE
Eval table empty with watch

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#146]
Using command line  --eval --watch  
results in empty set of evals, which remains empty even if I change the bodies of parameterless functions. See attached file.
Without --watch, the eval values are shown.
[WatchNoEval.scala.txt](https://github.com/epfl-lara/stainless/files/1562950/WatchNoEval.scala.txt)

**Comment by mantognini** [comment]
I think this is due to the changes introduced in https://github.com/epfl-lara/stainless/pull/115#issuecomment-345749392. Maybe the compact mode should be enabled through an command line option.
