### ISSUE TITLE
Release stainless library

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#157]
Release the jar that enables all Scala program to use stainless libraries, in particular from sbt
- publish in appropriate web repositories so it can be easily added and found from sbt
- add reasonable data structures that are usable (e.g. certain search trees)
- reduce surprises if someone tries to execute stainless libraries (if must fail, do it informatively)
- make it easy to eliminate contract checks being done at run time
- if possible, make it possible to get the most common functionality including List by simple import stainless._ by using type aliases and forwarding definitions (like Scala's prelude, but still explicit)

**Comment by romac** [comment]
FYI the Stainless library is has been published at https://bintray.com/epfl-lara/maven/stainless-library since b65d300.

**Comment by romac** [comment]
Re-opening since we do not currently publish them properly (missing .class and scalaVersion set to 2.12.8 instead of 2.12).

**Comment by romac** [comment]
Actually, the current behaviour is correct, as people should not depend directly on the library but rather use the sbt plugin.
