### ISSUE TITLE
Exception: java.lang.NoSuchMethodError: scala.math.BigInt.$greater$eq

### ISSUE THREAD

**Issue by ceilican** [epfl-lara/stainless#162]
Hi! I wanted to run my Scala program that is using Stainless's `List`.  Because Stainless has been neither released (#157) nor integrated with SBT (#155) yet, I decided to generate a fat jar for Stainless and include it in my project's `lib` folder as an unmanaged dependency. I did that using the "sbt-assembly" plugin, and I manually merged the "core" and "frontends/library" sources, because I did not know how to tell sbt-assembly to generate a separate jar file for the sources in "forntends/ibrary".

Well, probably something went wrong, because I'm getting the following runtime exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.math.BigInt.$greater$eq(Lscala/math/BigInt;)Z
	at stainless.collection.List$$anonfun$size$1.apply(List.scala:19)
	at stainless.collection.List$$anonfun$size$1.apply(List.scala:19)
	at scala.Predef$Ensuring$.ensuring$extension2(Predef.scala:316)
	at stainless.collection.List.size(List.scala:19)
	at stainless.collection.List.size(List.scala:18)
	at stainless.collection.List.length(List.scala:21)
```

This exception is strange, because `scala.math.BigInt` does have the `>=` method, inherited from `Ordered`. And, if this method really didn't exist or couldn't be found for some reason, I would expect to see a compilation error when sbt-assembly tried to compile stainless and generate the jar, not a runtime error.

I think this problem would be solved if any of the following was done:

1. Release stainless, allowing users to manage the dependency through `build.sbt` with something like: `libraryDependencies += "org.stainless" % "stainless" % "0.1".

2. Define an SBT task in `https://github.com/epfl-lara/stainless/blob/master/build.sbt` to generate a proper fat jar for stainless, allowing users to use Stainless as an unmanaged dependency.

**Comment by samarion** [comment]
I believe the `BigInt` error comes from not compiling against the stainless library (for some reason I don't understand). We now have some support for a fat jar as well as an sbt plugin so I'll be closing this issue. Further developments on the release and fat jar can be tracked at https://github.com/epfl-lara/stainless/issues/157.
