### ISSUE TITLE
Termination problem with non-strict positive types

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#168]
Stainless labels p and x as terminating, but p()(x()) does not terminate. After the definition of p and x, I've tried putting the example in a form where the body of every lambda is a named function (still reported as terminating).

The example uses the same type `A` as in https://github.com/epfl-lara/stainless/issues/167.

```scala
object Termination extends App {
  case class A(m: (A => Boolean) => Boolean)
  
  def p(): A => Boolean = y => y.m(p())
  def x(): A = A(p => p(x()))

  // p()(x()) reduces to x().m(p()) and
  // x().m(p()) reduces to p()(x()) (does not terminate)
}
```

`TerminationIR` is another form for `Termination`, where p1 and x1 correspond to p and x respectively

```scala
object TerminationIR extends App {
  case class A(m: (A => Boolean) => Boolean)

  // f is not recursive, and does not directly refer to named functions
  def f(y: A, pp: () => A => Boolean) = y.m(pp())

  // p1 only invokes f, and itself under a lambda
  // saying that p1 is "terminating" is probably the issue?
  def p1(): A => Boolean = y => f(y, () => p1())

  // x1 refers to app, which is non-recursive, and to x1() itself under a lambda
  def x1(): A = A(p => app(p,x1()))

  // app is non-recursive, and does not directly refer to named functions
  def app(p: A => Boolean, x: A) = p(x)
}
```

Edit: fixed a typo, the body of x1 must refer to x1(), not the x from the non-IR form (which is independent)

Edit2: separated both forms for better readability

**Comment by jad-hamza** [comment]
This example is related, but doesn't use datatypes. Stainless is able to catch the non-termination here: foo()() reduces to run(foo) reduces to foo()()

```scala
object Termination extends App {
  def foo(): () => Unit = () => run (() => foo())
  def run(h: () => () => Unit) = h()()
}
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/9065117d8a48503b7e744daadc15bc86a3baec3f

**Comment by jad-hamza** [comment]
Thanks! Seems to be working now

There are still termination-related soundness issues that we should keep in mind, such as this version of zeros (found to be terminating, but is looping)

```scala
object Stream {
  case class SCons(x: BigInt, tail: () => SCons)
  def zeros(): SCons = SCons(0, () => zeros().tail())
}
```

**Comment by samarion** [comment]
That was another bug in the CFA (fixed in https://github.com/epfl-lara/stainless/commit/f0794afb3065d7a9304214e51ef53b1e0c62d987). There may still be other bugs, I need to discuss the CFA implementation with @ravimad.

**Comment by jad-hamza** [comment]
Yes, I'm adding this here for regression tests (found to be terminating as well)

```scala
object Stream {
  case class SCons(tail: () => SCons)
  def fib(): SCons = SCons(() => SCons(() => fib().tail().tail()))
}
```

**Comment by ravimad** [comment]
@samarion: Jad and I are working on making the reasoning for cyclic datatypes sound, which may now not need a CFA analysis (or it is not at least not clear until now). So possibly hold on for sometime, with fixing bugs. We have to change the algorithm a bit more.  But handling of "measures" of functions will remain the same, though theoretically we are trying to unify that with the reasoning for cyclic structures.
