### ISSUE TITLE
How to use Stainless on multiple files?

### ISSUE THREAD

**Issue by ceilican** [epfl-lara/stainless#169]
Suppose that:
1. my project has two files: `A.scala` and `B.scala`
2. `B.scala` imports a class `C` defined in `A.scala`

If I try to run Stainless on `B.scala`, Stainless outputs the following error message:

`error: not found: type C`.

How can I circumvent this?

**Comment by jad-hamza** [comment]
Can you try invoking on `A.scala B.scala` (or `*.scala`)

**Comment by ceilican** [comment]
I'm without time to try it now. And I also had to stop using Stainless on that particular project for now, and I would have to roll back to an older version of my project to try Stainless again. Nevertheless I just wanted to comment that I didn't try calling Stainless with multiple file arguments, because Stainless usage instructions say the following:

```
$ ./stainless --help
[  Info  ] Stainless verification tool (https://github.com/epfl-lara/stainless)
[  Info  ] 
[  Info  ] Usage: stainless [OPTION]... FILE...
[  Info  ] 
...
```

If it is possible to call Stainless with multiple file arguments, I would suggest changing the help message above to:

```
$ ./stainless --help
[  Info  ] Stainless verification tool (https://github.com/epfl-lara/stainless)
[  Info  ] 
[  Info  ] Usage: stainless [OPTION]... FILE(S)...
[  Info  ] 
...
```

**Comment by samarion** [comment]
We now have an sbt plugin ([see documentation](https://github.com/epfl-lara/stainless/blob/master/core/src/sphinx/installation.rst#sbt)) which should make using stainless a bit easier for new projects. I also updated the help message, so I'm closing this issue.
