### ISSUE TITLE
List of side effecting JVM methods

### ISSUE THREAD

**Issue by fommil** [epfl-lara/stainless#171]
in scalafix we can restrict what can be called... do you have a comprehensive list of symbols in the jvm stdlib that get as side effecting?

From there, we can use bytecode analysis to create banlists for any jar.

**Comment by samarion** [comment]
I'm afraid we don't have such a list. I'm not actually sure we support _any_ symbols from the JVM stdlib. I think that basically the only things that aren't defined within `frontends/library` that we support are
- `scala.Predef.Ensuring` for `ensuring`
- `scala.Predef.require`
- `scala.Predef.assert`
- `scala.Predef.arrayOps` for `update` and `size`
- `scala.Predef.ArrowAssoc` for `->`
- `scala.Predef.identity`
- `scala.Predef.locally`

**Comment by samarion** [comment]
Closing as such analysis would make more sense outside of Stainless (we kind of assume closed world for what we verify).
