### ISSUE TITLE
Detecting integer underflow in class variable

### ISSUE THREAD

**Issue by ak807** [epfl-lara/stainless#172]
Hello,

My first attempt was to write the following program:

```scala
class underflow_demo {

    var state : Int = -1000

    def decrement(stride : Int) = {
        require(stride > 0)
        state -= stride
    } ensuring(_ => old(state) > state )
}
```

The error that I got from this was the following:

`[Internal] Error: Old is only defined on "this" and variables.`

I then tried the following:

```scala
case class underflow_demo(var state: Int) {

    def decrement(stride : Int) = {
        require(stride > 0)
        state -= stride
    } ensuring(_ => old(state) > state )
}
```

This time I got the following error:

```
[Internal] Error: Not well formed definition def decrement(thiss: underflow_demo, stride: Int): (Unit, underflow_demo) = {
[Internal]   require(stride > 0)
[Internal]   val thiss: underflow_demo = underflow_demo(thiss.state - stride)
[Internal]   ((), thiss)
[Internal] } ensuring {
[Internal]   (x$1: (Unit, underflow_demo)) => state < x$1._2.state
[Internal] }
[Internal] 	because Unknown variables: state$11.
```

So then I tried something similar to [this](http://stainless.epfl.ch/doc/imperative.html#annotations-for-imperative-programming):  

```scala
object underflow_demo { // If I replace `object` with `class` I get some warnings as well. Why ?

    case class state_wrapper(var state: Int)

    def decrement(s: state_wrapper, stride : Int) = {
        require(stride > 0)
        s.state -= stride
    } ensuring(_ => old(s.state) > s.state )
}
```

And got the error:

`[Internal] Error: Old is only defined on `this` and variables.`

How can I make this example work ? Note that the `state` needs to be in a (case) class one way or another. Would that be possible ?

P.S.: I am new to Scala and fv so I do apologize in advance if I have missed a fundamental concept here.

Thanks in advance !

**Comment by samarion** [comment]
We don't support extracting non-case classes which is why your first attempt won't work. The error reporting is not very clear about this, we still need to improve it.

Both your second and third solutions are almost correct. For the second one, although the syntax makes `state` seem like a variable, you're actually referring to `this.state`, so the old state must be accessed as `old(this).state`. Same for your third attempt where you need to refer to `old(s).state` to access the previous state.

**Comment by ak807** [comment]
I see. The error message now makes more sense ! I can confirm that both my second and third attempt as described above now work using `old(this).state` and `old(s).state`.
Thanks a lot !

**Comment by jad-hamza** [comment]
cc: @romac @romainjufer
We got the same issue when trying to use `old(state)` and we were a bit confused about the error message: 

> because Unknown variables: state$11

Should we translate that to `old(this).state` automatically or maybe just improve the error message?

**Comment by romac** [comment]
Yeah I guess we could extract ‘old(this.x.y.z)’ as ‘old(this).x.y.z’ automatically.

**Comment by romac** [comment]
Closing because we now properly report an error on invalid usage of `old`.

eg.

```scala
import stainless.lang._
object test {
  case class underflow_demo(var state: Int) {
      def decrement(stride : Int) = {
          require(stride > 0)
          state -= stride
      } ensuring(_ => old(state) > state )
  }
}
```

=>

```
[info] [ Fatal  ] test.scala:10:23: Stainless `old` is only defined on `this` and variables.
[info]                } ensuring(_ => old(state) > state )
[info]                                ^^^^^^^^^^
```
