### ISSUE TITLE
Barbanera/Berardi's paradox (polymorphism + excluded middle)

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#173]
~~[This example](https://gist.github.com/jad-hamza/62ac1947b28ff05113463b861073f4b8)~~[This example](https://gist.github.com/jad-hamza/62ac1947b28ff05113463b861073f4b8#file-berardi4-scala), accepted by Stainless, shows the inconsistency between impredicative polymorphism for types + excluded middle for all types. It is copied from:

- https://github.com/FStarLang/FStar/blob/master/examples/paradoxes/berardi_minimal.fst
- https://github.com/FStarLang/FStar/issues/360
- https://coq.inria.fr/library/Coq.Logic.Berardi.html
- https://cstheory.stackexchange.com/questions/21836/why-does-coq-have-prop (the first and second answers are interesting)

I don't fully understand the example (in particular I missed how Stainless is able to go from L72 to L73), and am not sure how we should fix it. `cem` is definitely suspicious! The other possibility is to have a hierarchy of types, that will prevent instantiating U.u on U itself.

This is also related is a larger sense to the implementation of the Scala type system: https://github.com/epfl-lara/stainless/issues/36 https://github.com/epfl-lara/stainless/issues/38 https://github.com/epfl-lara/stainless/issues/39.

**Comment by jad-hamza** [comment]
At the moment these examples don't go through anymore and need to be reviewed. `Berardi.scala` has some conditions that do not go through and `Berardi2.scala` gives an internal error.

**Comment by jad-hamza** [comment]
I updated the example so that the contradiction goes through again (see file [Berardi3.scala](https://gist.github.com/jad-hamza/62ac1947b28ff05113463b861073f4b8#file-berardi3-scala)).

**Comment by vkuncak** [comment]
This appears to be now checked and error is reported. But is it rejected for the right reason?
`
Quantification jixx[(A) => Boolean, (B) => Boolean](x$165, x$166, x$120) does not fit in supported fragment.
[ Error  ]   Reason: Can't guarantee model for complex matchers.
`

**Comment by jad-hamza** [comment]
Have you tried the latest version [Berardi3.scala](https://gist.github.com/jad-hamza/62ac1947b28ff05113463b861073f4b8#file-berardi3-scala)? I tried and it just fails on `mkFalse` (but that should go through, I'll try to fix it)

**Comment by jad-hamza** [comment]
It's now fixed in [Berardi4.scala](https://gist.github.com/jad-hamza/62ac1947b28ff05113463b861073f4b8#file-berardi4-scala) (I added a `save` function to make sure that the contradiction `f` is visible to the solver in `mkFalse`). Actually `mkFalse` is probably not needed, I could just use `save` directly in places where I need to use a contradiction.

**Comment by vkuncak** [comment]
The real solution for this is #452 but we can explore other remedies as well.

**Comment by vkuncak** [comment]
The example is now rejected with the default configuration. The old vc gen is going away.
