### ISSUE TITLE
Quantification over an empty type

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#174]
Stainless is able to deduce `false` from the fact that `forall((x: False) => false)` (in the first branch of the `if`)

```scala
import stainless.lang._

object Foralls {
  case class False() {
    require(false)
  }

  def lemma() = {
    if (forall((x: False) => false)) {
      assert(false)
    } else {
      val f = choose((x: False) => true)
      assert(false)
    }
  }
}
```

I suspect this bug helped https://github.com/epfl-lara/stainless/issues/173 go through more easily, so once we fix this we should probably modify https://github.com/epfl-lara/stainless/issues/173 again to make the inconsistency "proof" go through.

**Comment by samarion** [comment]
Empty types have now been disallowed in https://github.com/epfl-lara/stainless/commit/3595e2fed2d00d89190868b2371c97aa58c2b6b6
