### ISSUE TITLE
Crash when using forall(p)

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#18]
This file fails with 
> Exception in thread "main" inox.ast.Definitions$FunctionLookupException: Lookup failed for function with symbol forall

but works well if we replace forall(p) with forall((t: T) => p(t))

```scala
import stainless.lang._

object Intro {

  def test[T](p: T => Boolean): Boolean = {
    forall (p)
  } 

}
```

**Comment by samarion** [comment]
Fixed
