### ISSUE TITLE
Inox internal crash, assertion failed

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#181]
We found an Inox crash with @romac (removing any assert makes the crash go away)

https://gist.github.com/jad-hamza/5a501b40afce3fa9fc086c2f155d22e0

```scala
import stainless.lang._

object stlc {
  sealed abstract class Term

  final case class Var(id: BigInt)    extends Term
  final case class App(arg: Term)     extends Term
  final case class Abs(body: Term)    extends Term

  def ignoreX(x: BigInt) = true

  def f(t: Term): Boolean = {
    t match {
      case Var(y) =>
        assert(ignoreX(y))
      case Abs(body) =>
        assert(f(body))
      case App(arg) =>
        assert(forall { (x: BigInt) => ignoreX(x) })
        assert(f(arg))
    }
    true
  }
}
```

**Comment by jad-hamza** [comment]
Probably related (with a similar error output)

```scala
import stainless.lang._

object Main {
  def g(w: BigInt) = true

  def f() = {
    assert(forall((w: BigInt) => { g(w); true }))
  }
}
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/011498d8f93ad1e0291682dff28310f61969cbdb and https://github.com/epfl-lara/stainless/commit/20bb53c3b0c5e1d10b521bf47efc9d6bb6acd9df
More related fixes in https://github.com/epfl-lara/inox/commit/90eb7bb171d04d714dfaaec6b1f59b3db23583a3
