### ISSUE TITLE
Reporting Int to BigInt conversions

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#191]
```scala
object IntBigInt {
  def f(i: BigInt) = i
  def g(i: Int) = f(i)
}
```

This example crashes with a long stack trace ending with:
> [Internal] Conversion from Int to BigInt

```scala
object IntBigInt {
  def g(i: Int) = BigInt(i)
}
```

This one crashes with a trace ending with:
> [Internal] Non-literal BigInt constructor

Should we report these unsupported conversions as errors instead? (with a line number)

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/b0338b2992710adf18c46cf63a22ab837ceacde8 and https://github.com/epfl-lara/stainless/commit/6c8602c0097f30c048e1f2341598f12954726353
