### ISSUE TITLE
Summary table has a display issue for multiline models

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#195]
```scala
object Looping {
  def looping(p: Boolean => Boolean): Boolean = {
    if(p(true)) looping(p)
    else true
  }
}
```

run with `--termination` produces the table: https://i.imgur.com/nZ6fxJn.png

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/56c32b1d35598091cf7a753b71e9760a8e777b10
