### ISSUE TITLE
Kill stuck builds on larabot

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#198]
A couple of my latest builds seem to be stuck (#2248, #2257), and should probably get killed manually.

This is weird because some other builds have been properly killed after 30min (eg. #2251). There might be an issue somewhere with larabot that we should investigate.

**Comment by samarion** [comment]
This seems like an issue with [runlim](http://fmv.jku.at/runlim/). If you have a better alternative, we can consider updating how larabot limits resource bounds.

**Comment by romac** [comment]
[This build](http://laraquad4.epfl.ch:9000/epfl-lara/stainless/build/2264) needs to be killed as well.

**Comment by romac** [comment]
Also, could you raise the global timeout to 1 hour or so? With the new `PartialEvalSuite`, the overall running time of the test suite goes over 30min, and thus gets killed before it has a chance to finish.
