### ISSUE TITLE
Typing issue with sets

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#20]
Because of the minus (-) operator, Stainless/Inox crashes on the following file with the exception: 

> Exception in thread "main" inox.ast.TypeOps$TypeErrorException: Type error

The crash disappears when replacing "- x" with "-- Set(x)"

```scala
import stainless.collection._
import stainless.lang._

object Content {

  def wrongTheorem[A](l: List[A], x: A): Boolean = {
    l.content == l.content - x
  
  } holds
  
}
```

**Comment by samarion** [comment]
Fixed
