### ISSUE TITLE
Crash when using type members

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#206]
CC: @romac @RomainJufer

We obtained a crash on this example that uses type members. I guess the warnings that are emitted in the beginning (about type members) should be errors?

```scala
object SC {
  abstract class M {
    type T
    def c(t: T): Unit
  }
  
  case class A(var x: BigInt)
  
  case class F() extends M {
    type T = A
    def c(t: T) = {
      t.x += 2
    }
  }
}
```

https://gist.github.com/jad-hamza/ae7d82e0bedc4b6d99de0f33d7498f39

**Comment by samarion** [comment]
Yes, they should be errors. Fixed in https://github.com/epfl-lara/stainless/commit/c1d6e56f2181efc8a3858ed55d11d9d87a72c005
