### ISSUE TITLE
Support for generic copy() method

### ISSUE THREAD

**Issue by pjmkrpg** [epfl-lara/stainless#21]
I tried to compile Leon/Stainless code using the generic `copy()` method for generic case classes (see [here](http://stackoverflow.com/questions/7249396/how-to-clone-a-case-class-instance-and-change-just-one-field-in-scala)), but it seems that it is not yet in the Stainless library. Is it possible to provide support for this construct?

**Comment by MikaelMayer** [comment]
We appreciate your feedback !
Until we do it ourselves in a long-term future, feel free to submit a PR and we will review it gladly.
