### ISSUE TITLE
Choose satisfiability VC fails to prove

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#213]
```scala
import stainless.lang._

object Solver {
  def theorem() = {
    choose((b: BigInt) => b >= 0)
  }
}
```

```
[  Info  ]  - Now solving 'choose satisfiability' VC for theorem @5:5...
[ Debug  ] ¬∀b: BigInt. ¬(b >= 0)
[ Debug  ] Solving with: U:smt-z3
[ Error  ] Quantification x$66 < x$68 does not fit in supported fragment.
[ Error  ]   Reason: No matchers found.
[ Error  ] Model obtained was:
[ Error  ]   (Empty model)
[  Info  ]  - Result for 'choose satisfiability' VC for theorem @5:5:
[Warning ]  => UNKNOWN
 ```

**Comment by jad-hamza** [comment]
@samarion, we were discussing with @romac and @romainjufer adding an optimization to make these VCs go through. Is there already something in Stainless or Inox we can use?

**Comment by romac** [comment]
Whats the optimisation you are thinking of? It seems to me that such a VC should go through no matter what, shouldn't it?

**Comment by jad-hamza** [comment]
In this example, Inox must prove that `¬¬∀b: BigInt. ¬(b >= 0)` is unsat. I assume Inox already simplifies the double negation? And then Inox must prove that `∀b: BigInt. ¬(b >= 0)` is unsat. Instead here it would be enough to check that `b >= 0` is sat.

But this is really a degenerate example since there are no free variables, and so there is no alternation of quantifiers in that example. The other examples we had in the project will have an alternation of quantifiers, so they will more complicated to simplify.

**Comment by samarion** [comment]
I've already implemented an optimization that transforms the choose unsat check into a sat one when there are no quantifier alternations, but it hasn't made its way into master yet because I need to slightly change how caching works for this (sat or unsat check must be part of the key).

For quantifier alternations, I don't really know how to improve the current system other than port synthesis from Leon.

**Comment by samarion** [comment]
Fixed (for no alternations) in https://github.com/epfl-lara/stainless/commit/3595e2fed2d00d89190868b2371c97aa58c2b6b6
