### ISSUE TITLE
Z3 exception with higher order function

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#23]
I get an exception with this file with Z3 native, but --solvers=smt-z3 works well

> com.microsoft.z3.Z3Exception: Sorts (BigInt) => BigInt and (BigInt) => fun1[BigInt, BigInt] are incompatible

```scala
import stainless.lang._

object Incompatible {

  def false_theorem(f: BigInt => (BigInt => BigInt)) = {
    false
  } holds
  
}
```

**Comment by samarion** [comment]
Thanks, fixed in https://github.com/epfl-lara/inox/commit/5f77bffff3d4fc3e82c5bf8a323bb779e61dd0f4
