### ISSUE TITLE
Uninitialized vars in trait yield wrong message of error

### ISSUE THREAD

**Issue by RomainJufer** [epfl-lara/stainless#283]
@jad-hamza 

```scala
trait Foo {
  var id: BigInt

  def updateId(newId: BigInt) = {
    id = newId
  }
}
```

Yield the message

[ Error  ] updateId$0 depends on missing dependencies: id_=$0.
[Internal] Missing some nodes in Registry: id_=$0

While if we initialize the var we get 

[ Error  ] Inheritance/Foo.scala:6:3: Vars are not allowed in class bodies in Stainless.
             var id: BigInt = BigInt(0)

**Comment by samarion** [comment]
Fixed by https://github.com/epfl-lara/stainless/pull/313
