### ISSUE TITLE
Tuple6 exception

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#29]
There is a crash when using tuples with 6 elements or more:

> Exception in thread "main" stainless.extraction.oo.Definitions$ClassLookupException: Lookup failed for class with symbol Tuple6

```scala
object Tuples {
  def f() = (0,0,0,0,0,0)
}
```

**Comment by mantognini** [comment]
I need to modify the code extractor for bitvector anyway, do you want me to generalise support for tuple N at the same time?

**Comment by samarion** [comment]
Sure.

**Comment by mantognini** [comment]
Support for this is included in #33.
