### ISSUE TITLE
Mutable variable is not updated properly after mutation by a lambda

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#322]
The assertion is reported as invalid (`x == 0` instead would be valid), as the update by `g()` is ignored.

```scala
object Test {
  def f() = {
    var x = 0
    val g = () => { x = x + 1 }
    g()
    assert(x == 1)
  }
}
```

Should we reject these kinds of programs with the fragment checker?

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/4682fea2c96db70b6e196c0531d719d8aa4540bf
