### ISSUE TITLE
CVC4 solver only supported up to version 1.4

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#325]
With 1.6 I get:

$ stainless-scalac frontends/benchmarks/verification/valid/PartialCompiler.scala --solvers=smt-cvc4
```scala
[...]
[ Fatal  ] Unexpected error from cvc4 solver: Parse Error: <stdin>:102.85: expected constant term inside array constant, but found nonconstant term:
[ Fatal  ] 
[ Fatal  ]   ...as const (Array String!15 Option!4)) dlft!21)))) b!105))
[ Fatal  ]                                           ^
[ Fatal  ] 
[ Fatal  ] the term: dlft!21
[...]
```

**Comment by jad-hamza** [comment]
See also https://github.com/epfl-lara/inox/issues/77 for Z3 compatibility

**Comment by samarion** [comment]
This is a limitation of CVC4: https://cs.nyu.edu/pipermail/cvc-users/2017/000879.html
I added a test in Inox at https://github.com/epfl-lara/inox/commit/fcc5f9a844e01e472c2065b0a1ba3711e4b2be15 to provide a slightly better error message.
