### ISSUE TITLE
Ghost check too restrictive

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#345]
This is currently rejected by the Ghost checker. Should it be ok, since the whole function `f` is ghost?

```scala
import stainless.annotation._

object Ghost {
  case class Ghost(
    @ghost var x: BigInt
  ) {
    @ghost
    def f() = {
      val y = x // Right-hand side of non-ghost variable cannot be ghost
    }
  }
}
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/a5ea688b416d470e0a976f7133ffdb2c144b6424
