### ISSUE TITLE
How to run a single test?

### ISSUE THREAD

**Issue by OlivierBlanvillain** [epfl-lara/stainless#35]
I think it would be useful to add a paragraph to [`installation#running-tests`](https://github.com/epfl-lara/stainless/blob/master/core/src/sphinx/installation.rst#running-tests) explaining how to run tests individually.

In my case I'm adding new entries in `frontends/benchmarks/extraction`, is it sufficient to run the following:?

```
$ sbt 'stainless-scalac/run frontends/benchmarks/extraction/new-test.scala'
$ sbt 'stainless-dotty/run frontends/benchmarks/extraction/new-test.scala'
```

**Comment by mantognini** [comment]
I guess it should be as it will in addition run verification on the extracted AST. But this would not directly apply to other test suits.

Alternatively, you can use a hidden feature that I just discovered:

```
it:testOnly *ExtractionSuite* -- -z "in termination/looping"
```

will filter the the test suits (`testOnly`) and the subtests (the one matching `in termination/looping` in their title). Some additional stuff is still printed but only the relevant tests should be run I think.

In your case, you could run `it:testOnly *ExtractionSuite* -- -z "in extraction"` I believe. Does that help?

**Comment by OlivierBlanvillain** [comment]
:+1:

**Comment by mantognini** [comment]
This is superseded by #47.
