### ISSUE TITLE
Running the stainless command-line on test suite leads to internal error

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#359]
Running this:

> stainless-scalac frontends/benchmarks/imperative/valid/TraitVar1.scala 

gives:

```
[Internal] Error: Not well formed definition class Bar((stuff: BigInt) @var) extends Foo 
[Internal]      because Abstract methods TraitVar2.Foo.prop_$eq were not overriden. Trace:
```

This file runs ok in the integration tests, so this is maybe due to a dependency computation problem?

**Comment by samarion** [comment]
Yes, there is an issue with the dependency computation. I believe the `addEdgesToOverrides` is the culprit but I don't know exactly what we're doing wrong.

**Comment by samarion** [comment]
Fixed by https://github.com/epfl-lara/stainless/pull/365
