### ISSUE TITLE
Support for anonymous class

### ISSUE THREAD

**Issue by OlivierBlanvillain** [epfl-lara/stainless#36]
I believe this could be part for the supported subset of Scala. Here is a minimised example that doesn't pass extraction:

```scala
object Test {
  val o = new Object {}
  println(o)
}
```

Scalac will desugar that code into a local class definition and an instantiation. It looks like nested class definition are at fault; the following also fails to pass extraction:

```scala
object Test {
  class C {
    def f: Unit = {
      class D
      ()
    }
  }
}
```

**Comment by romac** [comment]
I am currently working on anonymous classes support in Stainless, although my implementation is for now restricted to module-level declarations where the anonymous class extends a user-defined trait or abstract class such as in:

```scala
trait Foo[A] {
  def bar: A
}

def baz[A](x: A) = new Foo[A] {
  override def bar: A = x
}
```

or 

```scala
trait Foo[A] {
  def bar: A
}

object baz extends Foo[Int] {
  override def bar: Int = 42
}
```

I plan to extend this to support local declarations as well, but this will have to wait until the semester is over.
