### ISSUE TITLE
Caching issue in SuperCalls phase

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#367]
We discussed a caching issue with @romac in the `SuperCalls` phase. It can be reproduced like this:

> $ stainless-scalac frontends/benchmarks/verification/valid/SuperCall6.scala --debug-phases=SuperCalls --debug=trees --debug-objects=Base$method1,method1,method2

The `funCache` for `method1` gets corrupted, @romac said we need to add some dependencies in the funCache (e.g. here the key for `method1` would contain `method2`). We can also make a `mustDuplicate(fd: FunDef): Boolean` function and then add that boolean as a `ValueKey` to the `funCache` keys.

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/8b78ad3fcdcbad567377ce134bfdba9ebe8e8206
