### ISSUE TITLE
Mismatch in semantics between Stainless and Scala can lead to runtime crashes

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#372]
While discussing the upcoming support for inner classes (#271) with @jad-hamza and @vkuncak, we realised that those introduce a semantics mismatch with Scala in some cases.

Consider the following program:

```scala
  abstract class Test {
    def bar: BigInt
  }

  def foo(outer: BigInt): Test = {
    case class Foo(y: BigInt) extends Test {
      def bar = outer
    }
    Foo(12)
  }

  def oops = {
    // Assertion verifies but crashes at runtime when compiled with scalac
    assert(foo(1) != foo(2))
  }
```

The mismatch happens because, within Stainless, the inner class `Foo` gets lifted to the top-level, and the free variable `outer` gets added as a field, essentially turning the code above into:

```scala
  case class Foo(y: BigInt, outer: BigInt)

  def foo(outer: BigInt): Test = {
    Foo(12, outer)
  }
```

This means that Stainless will consider `foo(1) != foo(2)` because `Foo(42, 1) != Foo(42, 2)`, while scalac's `equals` methods only checks the original fields of the case class.

It should be noted that the Scala semantics break referential equality, ie. `foo(1) == foo(2) ==> foo(1).bar == foo(2).bar` does not hold in Scala, while it does in PureScala.

Nonetheless, as shown above this mismatch can lead to runtime crashes, and we should therefore do something about this, for example disallow equality tests on classes with have inner subclasses

@samarion @jad-hamza @vkuncak Thoughts?

PS: This is not the only mismatch in equality semantics between Stainless and Scala, lambdas notably contribute to this issue as well:

```scala
val a = (x: BigInt) => x
val b = (x: BigInt) => x
assert(a == b)
```

verifies with Stainless but crashes with scalac.

**Comment by jad-hamza** [comment]
So we would use `==` (non-ghost) for types where Stainless and Scala coincide, and ghost `===` for lambdas, classes, etc. to refer to Stainless equality? And then we'd reject the Scala `==` for types that are not supported?

**Comment by romac** [comment]
Because we can not replicate Scala’s semantics and because we should be able to differentiate between the two usage, my opinion would be that we just reject such problematic usages whenever we can detect them.

**Comment by vkuncak** [comment]
@romac : I think Scala does the wrong thing here. foo(1) and foo(2) are clearly behaving differently and it makes no sense to say that they denote the same value. It appears sufficient to disallow equality on classes that contain an inner class that captures variables. To make sure that we can make this check, maybe we can disallow (in user code, non-transformed) equality on non-sealed abstract classes?
