### ISSUE TITLE
MutabilityAnalyzer misses invalid type instantiations

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#384]
Here we shouldn't be able to instantiate `B[T]` with `A`. We need to add a traverser in `MutabilityAnalyzer` that checks whether all class types satisfy the mutability conventions.

```scala
import stainless.annotation._

@mutable trait A
trait B[T]
trait C {
  def f(b: B[A]): Unit
}
```

**Comment by samarion** [comment]
Indeed, I thought we already had this check in `EffectsChecker` but it seems it's still missing.
We can probably adapt the traverser in `EffectsChecker` to also traverse types, but we'll need to make it into a top-level traverser and call it on all functions and sorts in the program.
