### ISSUE TITLE
Ghost annotation is not extracted for accessors

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#387]
This example fails with the error:

```scala
import stainless.annotation._

trait TT {
  @ghost var x: BigInt
}
```

> [ Fatal  ] Right-hand side of non-ghost field assignment cannot be ghost

It looks like the `@ghost` annotation is ignored during extraction. The `Sealing` phase also ignores these flags when overriding accessors and creating fields (see https://github.com/epfl-lara/stainless/pull/388).

> $ stainless-scalac --debug=trees --debug-objects=x.* --debug-phases=PartialFunctions File.scala

```scala
[ Debug  ] Symbols before PartialFunctions
[ Debug  ] 
[ Debug  ] -------------Functions-------------
[ Debug  ] @accessor
[ Debug  ] @abstract
[ Debug  ] @method(TT)
[ Debug  ] def x_=((x$1: BigInt) @ghost): Unit = <empty tree>[Unit]
[ Debug  ] 
[ Debug  ] @accessor
[ Debug  ] @abstract
[ Debug  ] @method(TT)
[ Debug  ] def x: BigInt = <empty tree>[BigInt]
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/3a45af6f7f50f59b1fa58469fb0f0a51383f75cc
