### ISSUE TITLE
`val` in trait is assumed to be modified after call to extern function 

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#415]
```scala
import stainless.annotation._

@mutable
trait T {
  val x: BigInt
  def havoc(): Unit
}

object ValModification {
  def f(t: T) = {
    val y = t.x
    t.havoc()
    assert(y == t.x)
  }
}
```

The VC for this assertion returns a counter-example but `t.x` shouldn't change. I think this is a known issue (we already discussed something similar with @samarion). Here the problem is that the `AntiAliasing` phase assumes that `havoc` transforms `t` into a completely new `T` element (unrelated to `t`).

```scala
[ Debug  ] Symbols after AntiAliasing
[ Debug  ] 
[ Debug  ] -------------Functions-------------
[ Debug  ] @extern
[ Debug  ] @derived(havoc)
[ Debug  ] @synthetic
[ Debug  ] def havoc(thiss: TExt): (Unit, TExt) = <empty tree>[(Unit, TExt)]
```

We could make the transformation in `AntiAliasing` more precise (for `havoc`), either by directly constructing a new `T` which shares the old `val`'s, or we can keep it how it is now and just add a postcondition saying that the `val`'s of the input are equal to the `val`'s of the output.

**Comment by romac** [comment]
We discussed with @jad-hamza the possibility of surfacing the internal `@abstract` annotation, which would let us define `havoc` as follows:

```scala
@mutable
trait T {
  val x: BigInt

  @abstract
  def havoc(): Unit = {
    ???
  } ensuring { res =>
    this.x == old(this).x
  }
}
```

while still having Stainless check that `havoc` is indeed override in subclasses.

What do you think @samarion?

**Comment by samarion** [comment]
Doesn't the system already consider that definition of havoc to be abstract and check that it's overriden?

**Comment by romac** [comment]
It does now :)
