### ISSUE TITLE
Extraction of inlined functions in the dotty frontend

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#419]
```scala
import stainless.lang._
import stainless.annotation._

case class GhostInlineExtraction(@ghost var x: BigInt) {
  def f() = {
    ghost { x }
  }
}
```

The call to `ghost` is not extracted properly in the dotty frontend (due to some early inlining). I guess that's a known issue seeing that ghost benchmarks are ignored in the `DottyExtractionSuite`

```scala
[ Debug  ] Symbols before PartialFunctions
[ Debug  ] 
[ Debug  ] -------------Functions-------------
[ Debug  ] @method(GhostInlineExtraction)
[ Debug  ] def f: Unit = {
[ Debug  ]   val value: BigInt = this.x
[ Debug  ]   @unchecked ()
[ Debug  ] }
```

**Comment by romac** [comment]
A simple fix would be to remove the `@inline` annotation on the `ghost` function in `library/stainless/lang/package.scala`. Dotty is indeed a bit of a second-class citizen for now, especially with regard to ghost code, as we don't have an sbt plugin that performs ghost elimination yet.
