### ISSUE TITLE
Specify which arguments should the induction be performed over with @induct

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#420]
This would let us write

```scala
  implicit def listMonoid[A]: Monoid[List[A]] = new Monoid[List[A]] {
    override def empty: List[A] = Nil[A]()
    override def append(xs: List[A], ys: List[A]): List[A] = xs ++ ys

    @induct(xs)
    override def law_associativity(xs: List[A], ys: List[A], zs: List[A]): Boolean = {
      true
    }
  }
```

instead of

```scala
  @induct
  def lemma_List_append_associativity[A](xs: List[A], ys: List[A], zs: List[A]): Boolean = {
    ((xs ++ ys) ++ zs) == (xs ++ (ys ++ zs))
  }.holds

  implicit def listMonoid[A]: Monoid[List[A]] = new Monoid[List[A]] {
    override def empty: List[A] = Nil[A]()
    override def append(xs: List[A], ys: List[A]): List[A] = xs ++ ys

    override def law_associativity(xs: List[A], ys: List[A], zs: List[A]): Boolean = {
      lemma_List_append_associativity(xs, ys, zs)
    }
  }
```

If we just specify `@induct` in the first example, the induction will be performed over `this` instead of `xs`, ie. the first parameter of the function after method lifting. This might also be a problem when we have reified type arguments but I haven't checked yet.

**Comment by romac** [comment]
@jad-hamza You have something similar in the `smart` fork, right? Could you please point me to the relevant commits so that I can open a PR for it?

**Comment by jad-hamza** [comment]
It's not on `smart` yet, but in the Stainless `type-inference` branch https://github.com/jad-hamza/stainless/commits/type-inference
The commits are a bit spread out, would you like me to open a separate PR for it? The first commit was this one: https://github.com/jad-hamza/stainless/commit/96f8872293964d64f599ead5b772316af566bab1
but many fixes came on top

**Comment by romac** [comment]
Oh right! Thanks, I’ll do it myself don’t worry!
