### ISSUE TITLE
Release page?

### ISSUE THREAD

**Issue by hrj** [epfl-lara/stainless#45]
Where can I watch for releases? I am watching the project on GitHub but that tends to be too noisy for me, since I am nowhere in the league of contributing to it.

I don't see any milestones defined either. Can I just track point releases here: https://github.com/epfl-lara/stainless/releases
(via the RSS feed of that page)?

Thanks!

**Comment by romac** [comment]
Closing as we now publish releases on GitHub at https://github.com/epfl-lara/stainless/releases, and people can just use the `Watch releases only` feature that's been introduced recently.
