### ISSUE TITLE
Default values in case classes

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#481]
Default values in case classes are currently not supported and should be rejected properly. The error message is better in https://github.com/epfl-lara/stainless/pull/422 (because we get a type error at the point where `g` is defined), but it would still be better to reject these directly

```scala
object DefaultVal {
  case class G(val x: BigInt = 0)
  val g = G()
}
```

> [Internal] Missing some nodes in Registry: apply$default$1$0

**Comment by vkuncak** [comment]
Re-raised in #749 ?
