### ISSUE TITLE
Call to eq lead to internal error

### ISSUE THREAD

**Issue by redelmann** [epfl-lara/stainless#492]
Calling the method `eq` of `AnyRef` leads to an internal error.

Minimal example:
```scala
object Ex {
  def isEq(a: AnyRef, b: AnyRef): Boolean = a eq b
}
```
```
[ Error  ] isEq$0 depends on missing dependencies: Object$1, eq$0.
[Internal] Missing some nodes in Registry: Object$1, eq$0
[Internal] Please inform the authors of Inox about this message
```

**Comment by romac** [comment]
We currently do not currently support referential equality, as it does not really make sense for PureScala.
But yeah, we should be displaying a better error message via `FragmentChecker`.
