### ISSUE TITLE
Issue with quantifier instantiation

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#5]
Stainless/Inox report "UNKOWN" for the post-condition of "instantiate".

```scala
import stainless.lang._

object Forall {
    
  def isZero(a: BigInt) = a == 0
    
  def instantiate(a: BigInt) = {
    require(forall { (x: BigInt) => isZero(x) })
    
    isZero(a)
  } holds

}
```

I attached the tip file, also pasted here with renamed variables.
[Forall.scala-0.txt](https://github.com/epfl-lara/stainless/files/735070/Forall.scala-0.txt)

```smt
(define-fun isZero ((a Int)) Bool (= a 0))

(declare-const b Int)

(assert (not (=> (forall ((x Int)) (isZero x)) (isZero b))))

(check-sat)
```

**Comment by samarion** [comment]
Fixed in Inox (https://github.com/epfl-lara/inox/commit/8fc10a57bc57ba2dc5f1f934d065dc64823e8884) but I'm waiting on https://github.com/epfl-lara/stainless/pull/3 to get the fix into Stainless.

**Comment by samarion** [comment]
Fixed since the merge of https://github.com/epfl-lara/stainless/pull/3.
