### ISSUE TITLE
Support for type members

### ISSUE THREAD

**Issue by piu130** [epfl-lara/stainless#511]
This code:
```scala
abstract class Test {
  type A = BigInt
}
```
Prints this warning:
```
[Warning ] Test.scala:4:3: Could not extract tree in class: type A = BigInt (class scala.reflect.internal.Trees$TypeDef)
             type A = BigInt
```
Type A should be extractable as described [here](https://stackoverflow.com/questions/2498779/accessing-type-members-outside-the-class-in-scala#answer-2498994). Accessing the type with Test#A works.

Just wanted to report it. It has no priority for me.

**Comment by romac** [comment]
There is WIP support in #470
