### ISSUE TITLE
Why object can not extend trait/class?

### ISSUE THREAD

**Issue by piu130** [epfl-lara/stainless#520]
What properties of case object do you depend on to support only `case object B extends A` and not `object B extends A`?

```scala
trait A

object B extends A // Objects cannot extend classes or implement traits, use a case object instead
case object B extends A // works
```

**Comment by romac** [comment]
We only support Scala constructs which possess some notion of (structural) equality, which plain `objects` do not. So at the moment they can only be used as namespaces.

**Comment by piu130** [comment]
@romac Thanks for your answer. Maybe I don't understand your statement. Do you have a small example?

The following prints `true`:

```scala
object A

object HelloWorld {
  def main(args: Array[String]): Unit = println(A == A) // true
}
```

**Comment by romac** [comment]
AFAIK equality between plain objects relies on reference equality via `AnyRef's `equals' method, which is not a notion of equality that is currently supported within Stainless because it is purely a runtime property that we cannot really reason about (not to mention it can be used to break referential transparency IIRC).

@samarion @vkuncak Is that right?

**Comment by romac** [comment]
EDIT: forgot to mention parametric polymorphism above

**Comment by vkuncak** [comment]
@piu130 : it's best if you don't rely on built-in equality when you do not have to. Can you define your own equality for the application you need?

**Comment by vkuncak** [comment]
Comparison of non-case objects is rejected (somewhat obscure error message, @romac , but it's rejected), as it should be given our view of the stainless-supported sublanguage: (plain) object is for modules, whereas case object should behave like the algebraic data type.

**Comment by piu130** [comment]
Thanks for your answers. This is not my code I just tired to understand why it's not supported.

After examine some dummy code `Test.scala`:
```scala
object A
case object B
```
with `scalac -Xprint:parse Test.scala` it prints:
```scala
object A extends scala.AnyRef ...
case object B extends scala.Product with scala.Serializable ...
```
So it looks like you are right with AnyRef's and the other statements.

Scala does a lot more than just adding some methods to case classes/case objects as described on most webpages. Sorry I didn't know that.

Thanks again:)
