### ISSUE TITLE
Extraction of refinements

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#535]
@romac I'm opening this issue to remember the small example that we discussed:

```scala
object Identity {
  type Neg = { x: Int => x < 0 }
  def id[T](x: T): T = x
  def f() = id[{x: Int => x > 0}](1) + id[Neg](-1)
}
```

After extraction we get:

```scala
def f: Int = id[Int](1) + id[Neg](-1)
```

After the whole pipeline, we get:

```scala
def f: Int = id[Int](1) + id[{ x: Int | (x < 0) }](choose((res: { x: Int | (x < 0) }) => false))
```

**Comment by romac** [comment]
Specifically after TypeEncoding. Seems like there is a missing case somewhere to handle type applications to refinements.

**Comment by romac** [comment]
This now works, just added an extraction benchmark in #642.
