### ISSUE TITLE
Postcondition of @extern function is ignored

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#548]
Almost the same issue as https://github.com/epfl-lara/stainless/issues/404 (which is fixed)

```scala
import stainless.annotation._

object ExternPost {
  def truth(i: BigInt): Boolean = true

  @extern
  def f(n: BigInt): Unit = {
  } ensuring(_ => recursive(n, truth))

  def g(n: BigInt): Unit = {
    f(n)
    assert(recursive(n, truth))
  }

  def recursive(n: BigInt, p: BigInt => Boolean): Boolean = {
    if (n <= 0) true
    else recursive(n-1,p)
  }
}
```

The verification condition of the assertion in `g` doesn't go through:

```scala
val tmp: Unit = f(n)
recursive(n, truth)
```

Interestingly, removing the unused parameter `p` of `recursive` makes the VC go through.

**Comment by jad-hamza** [comment]
This is the `tip` file which is produced for that verification condition, I guess the problem is the equality between the lambdas? Inox reports unknown with or without `assume-checked=false`.

```smt
(declare-datatypes () ((Unit!1 (Unit!2))))

(define-fun-rec recursive!0 ((n!7 Int) (p (=> Int Bool))) Bool (ite (<= n!7 0) true (recursive!0 (- n!7 1) p)))

(define-fun truth ((i!12 Int)) Bool true)

(define-fun f!30 ((n!5 Int)) Unit!1 (choose x$1!9 Unit!1 (recursive!0 n!5 (lambda ((i!13 Int)) (truth i!13)))))

(declare-const n!6 Int)

(assert (not (let ((tmp (f!30 n!6))) (recursive!0 n!6 (lambda ((i!14 Int)) (truth i!14))))))

(check-sat)

; check-assumptions required here, but not part of tip standard
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/a6cbf8e2488fd2d3aa941963fca65eb5d370c698. I published a new version of Inox including the fix: 1.1.0-332-ga6cbf8e.

**Comment by jad-hamza** [comment]
Awesome! How was the non-simplification of `choose` causing the issue?

**Comment by romac** [comment]
Fixed by https://github.com/epfl-lara/stainless/pull/571

**Comment by samarion** [comment]
@jad-hamza: the call-merging simplifier was transforming both `truth` lambdas into
```scala
(x: BigInt) =>
  val x: BigInt = truth
  x
```
and the simplifier was only transforming the one outside the choose back into
```scala
(x: BigInt) => truth
```
so the two lambdas had different structures and were considered unequal by the solver.

The transformation that lifts calls into let bindings happens as a pre-processing step of the call-merging. Maybe the merging could be changed a bit to avoid this step, I'm not sure.

**Comment by jad-hamza** [comment]
What's the call-merging?

**Comment by samarion** [comment]
When two calls to the same function appear in both if-expression branches, they are merged into one call and the if-expression gets pushed into the parameters. This reduces the exponential blowup in unfolding.

**Comment by jad-hamza** [comment]
I see, thanks!
