### ISSUE TITLE
Preconditions of lambdas

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#55]
How does Stainless/Inox interpret preconditions of complex terms, such as `f(true)` in this example?
There seems to be an issue because the precondition of the application `Application(f(true), ())` in `g` should fail to verify.

```scala
import stainless.lang._

object LambdaPreconditions {
  def a() = {
    require(false)
    false
  } holds

  def f(b: Boolean): () => Boolean = {
    if (b) a
    else () => true
  }

  def g() = {
    assert(f(true)())
    assert(false)
  }
}
```

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/a7d6cec1bc6f270cc46f951bf5ffd13e00b2ae36
