### ISSUE TITLE
Semantic of decreases()?

### ISSUE THREAD

**Issue by BLepers** [epfl-lara/stainless#56]
```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   case class SharedState(val rqs:BigInt => List[BigInt]) {
      require(forall((id:BigInt) => rqs(id).forall(e => e < id && e >= 0)))
   }

   @induct
   def isTree(s:SharedState, content:List[BigInt], id:BigInt):Boolean = {
      require(content.forall(e => e < id && e >= 0) && id >= 0)
      decreases(id, content.size)


      content match {
         case Nil() => true
         case Cons(t, ts) =>
            isTree(s, ts, id) && isTree(s, s.rqs(t), t)
      }
   }
}
```

Not really an issue, but I was wondering if I understood correctly how "decreases" work. Does decreases(a, b) means that either a, or b decreases? (As in the previous example, either id or the size decreases.)

Also, is there a page, or a document somewhere that contains a list of "helpers" that can be used to reduce the proving effort, such as ``forall``, ``choose``, ``decreases``? (Am I missing any other tool/quantifier/...?)

Thanks :)

**Comment by samarion** [comment]
A call to decreases with multiple arguments uses lexicographic ordering:
(a1, b1) < (a2, b2) iff a1 < a2 || (a1 == a2 && b1 < b2)

If we were saying either a or b decreases, this wouldn't guarantee
termination!

About the proving effort, we unfortunately don't have one ATM. Maybe
@jad-hamza could write something up, he has the most experience with
writing proofs in Stainless.

**Comment by BLepers** [comment]
Ha, indeed, thanks for the reply! :)
