### ISSUE TITLE
Abstract class constructor arguments

### ISSUE THREAD

**Issue by BLepers** [epfl-lara/stainless#57]
```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   abstract class SchedEntity(val id:BigInt);
   case class Process(val _id:BigInt, val state: BigInt, val rq: List[BigInt], val task: BigInt,
      val quanta: BigInt, val load: BigInt) extends SchedEntity(_id) {
         require(load >= 1 && load <= 1024)
      }
   case class Runqueue(val _id:BigInt, val content:List[BigInt]) extends SchedEntity(_id);
}
```

Crashes: "Exception in thread "main" inox.ast.TypeOps$TypeErrorException: Type error ..."

Is there a proper/better way to do inheritance in stainless?

**Comment by samarion** [comment]
Hmm, I think abstract classes with arguments are not supported for now. Try
```scala
abstract class SchedEntity {
  val id: BigInt
}
```
or something like that.

We should have better error messages for this, but we're in the process of
adding more inheritance support to Stainless, so this might be supported in
the future.

**Comment by samarion** [comment]
Should now be correctly rejected by the scalac frontend.
We will later evaluate whether the same checks should be added to the experimental dotty frontend so I'm closing this for now.
