### ISSUE TITLE
Organization of tests and bolts

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#574]
At the moment we have examples and benchmarks a bit scattered around:
* Some examples in bolts
* Here in `frontends/benchmarks`
* Duplicates of `frontends/benchmarks/valid` in `frontends/benchmarks/typechecker`
* Other examples from the outside (for instance the `LeaderElection` example from https://github.com/epfl-lara/stainless-actors-example which is not ready yet)

Thanks to @romac, Bolts will now have its own sbt projects. We could move more examples from here (the ones that are worthy) to Bolts. The examples from the outside will also be moved to Bolts when ready.

That will help with the possibility of having tests on Bolts when we commit on Stainless and vice versa, I think that will add stability to the builds and help us catch bugs more quickly. What do you think?

In Bolts and in Stainless, there are examples that cannot be run by the type-checker because of features that are not supported yet (quantifiers, etc.). We can adapt the tests in Stainless (the ones that refer to Bolts) to take that into account.

A few more things:
* Eventually we should deduplicate the tests from `verification/valid` and `typechecker/valid`. One solution is to remove from `verification/valid` the ones that we ported to `typechecker/valid`, and only leave those that are not supported by the type-checker in `verification/valid` (e.g. with quantifiers).
* The examples from `imperative/valid` have not been ported yet to work with the type-checker.

**Comment by romac** [comment]
Moved to #687
