### ISSUE TITLE
Report counterexamples in metals + sbt plugin for invalid vcs

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#579]
Currently error reports do not include counterexamples. For use in sbt plugin + metals, it would be great if those were emitted, so that users can counterexamples in the right function when they hover.
Here is how invalid vcs are reported now:
http://lara.epfl.ch/~kuncak/invalid-scalac.png

**Comment by romac** [comment]
Definitely an oversight on my part, will fix that. In the meantime you should see the counter examples in the VS Code console.
