### ISSUE TITLE
Enable --strict-arithmetic by default?

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#598]

**Comment by jad-hamza** [comment]
Maybe we can require the option to be explicitly given (as `on` or `off`) as soon as we see the user using a bitvector type? Or show a warning when the option is not given?

**Comment by vkuncak** [comment]
We can switch default to on and have users turn it off when they do bitvector arithmetic.
What if we want the choice to depend on the file being verified?
Whereas I would not recommend mixing sound and unsound options in different modules, wrap around is correct by semantics yet warnings are useful, so we can freely mix what to do in which part of code.

**Comment by romac** [comment]
For modularity, users could annotate their operations with `@unchecked`, which will/should not trigger a VC for this particular operation.

If this comes up often in the codebase, nothing would stop a user from defining an implicit value class with unchecked operations.

For comparison, Rust provides `overflowing_*`, `checked_*`, and `wrapping_*` methods on integers.

From https://doc.rust-lang.org/std/primitive.u32.html:

```rust
pub const fn wrapping_add(self, rhs: u32) -> u32
```
> Wrapping (modular) addition. Computes self + rhs, wrapping around at the boundary of the type.

```rust
pub fn checked_add(self, rhs: u32) -> Option<u32>
```
> Checked integer addition. Computes self + rhs, returning None if overflow occurred.

```rust
pub const fn wrapping_add(self, rhs: u32) -> u32
```
> Wrapping (modular) addition. Computes self + rhs, wrapping around at the boundary of the type.

When using plain arithmetic operations it will:

> - In debug mode, arithmetic (+, -, etc.) on signed and unsigned primitive integers is checked for overflow, panicking if it occurs, and,
> - In release mode, overflow is not checked and is specified to wrap as two’s complement.
> 
> — http://huonw.github.io/blog/2016/04/myths-and-legends-about-integer-overflow-in-rust/

**Comment by romac** [comment]
Current output when running Stainless with `--strict-arithmetic` on the problematic benchmarks in `verification/valid/`): https://gist.github.com/romac/a75c7546041a320adbdcdccfa2ed30fe

**Comment by romac** [comment]
Some things there don't make sense.

For example, this function's postcondition is reported as invalid by both CVC4 and Z3:

```scala
  def identity3(x: Int): Boolean = {
    -(x / 2) == x / -2
  } ensuring(res => res)
```

Z3 counter-example: 1073741824
CVC4 counter-example: -1615331366

But:

```scala
scala> identity3(-1615331366)
res1: Boolean = true
```

and

```scala
scala> identity3(1073741824)
res3: Boolean = true
```

(and this is with `--check-models` + the VC being INVALID, so there seems to be a problem on our side)

**Comment by romac** [comment]
Found it, It's a bug in AssertionInjector where unary minuses are dropped in strict arithmetic mode.

**Comment by vkuncak** [comment]
Good catch!
