### ISSUE TITLE
Parsable yet readable console output

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#604]
Current console output performs formatting directly and ouputs characters beyond 7 bit ASCII to format tables. Unfortunately, this becomes a problem with long error messages or long file paths, both of which are important pieces of information; in such case the lines spill over and the table border reduces readability.

I suggest that we change the default console output to be some comma separated list of lines and expose such raw output to the user, so one can use simple scripts to trim columns that are of interest, possibly using `tput cols` to obtain actual terminal width.

**Comment by romac** [comment]
That would imho significantly decrease the UX of the default UI that Stainless provides. I doubt that most users will know which incantation of `cut`, `tr` and `tput` to use to make the output nicely display.

We could on the other hand enable this behind a flag, which might also be useful in other settings, eg. when one would like to process the output programatically or via a shell pipeline.

Alternatively (or in addition), we could query the terminal width ourselves, and trim long filenames and VC descriptions accordingly in the report.

**Comment by vkuncak** [comment]
@romac I mostly agree with your line of thought, actually. I think that extended characters are not so essential, but I do agree that tabulated formatting helps readability. Not that this is essential, but maybe using tabs makes formatting work even with proportional fonts?

I agree that we should ideally query terminal columns ourselves and truncate long files names (probably truncate the start of the file name path and leave the end). The code should be prepared to fall back to current thing if querying columns fails due to absent command or if a weird value is returned; it would be silly to reduce portability of Stainless due to this aspect.

**Comment by romac** [comment]
Closing in favour of #678.
