### ISSUE TITLE
require() on each element of an array?

### ISSUE THREAD

**Issue by kushti** [epfl-lara/stainless#63]
Assume I have a function which is doing something with positive integers, say

def fn(a:Array[Int]) = {
    require(a.length > 1)
    require(a.forall(_ > 0))
    a(0)
  }.ensuring(_ > 0)

gives "[ Fatal  ] The extracted program in not well typed."

Without "require(a.forall(_ > 0))" it works (but the function is invalid, obviously).

Any workaround possible?

**Comment by samarion** [comment]
You can use `forall((i: Int) => (i >= 0 && i < a.length) ==> a(i) > 0)` instead of `a.forall(_ > 0)`.
If you want a better syntax, you can try playing around with implicit classes. Unfortunately, you might not be able to use the exact same syntax since `Array.forall` is already defined.

**Comment by kushti** [comment]
def fn(a:Array[Int]) = {
    require(a.length > 1)
    require(forall((i: Int) => (i >= 0 && i < a.length) ==> a(i) > 0))
    a(0)
  }.ensuring(_ > 0)

is running fine, but fails to check post-condition:

[  Info  ]  - Now considering 'postcondition' VC for fn @34:14...
[Warning ]  => INVALID
[Warning ] Found counter-example:
[Warning ]   a: Array[Int] -> Array(-2147483647, -2147483647)
[Warning ]   i: Int        -> 0

**Comment by samarion** [comment]
Ah sorry, I hadn't noticed but you can have at most one `require` statement in your function body. You can rewrite your function to
```scala
def fn(a:Array[Int]) = {
  require(a.length > 1 && forall((i: Int) => (i >= 0 && i < a.length) ==> a(i) > 0))
  a(0)
}.ensuring(_ > 0)
```

**Comment by kushti** [comment]
Works perfectly, thanks a lot!
