### ISSUE TITLE
Is possible to support mill build system?

### ISSUE THREAD

**Issue by sequencer** [epfl-lara/stainless#634]
sbt is a little slow now.
and if it is possible to add support mill for faster and smaller runtime overhead cost?

**Comment by romac** [comment]
> sbt is a little slow now.

Agreed, things should get much better with sbt 1.3, thankfully :)

> and if it is possible to add support mill for faster and smaller runtime overhead cost?

I don't enough about Mill to say whether or not it is possible, sorry. You are welcome to try though, but I cannot promise we will maintain the Mill build file, as we at the moment do not have the work force to support every build tool out there (cbt, mill, fury, etc.), unfortunately.
