### ISSUE TITLE
Lambda crashes

### ISSUE THREAD

**Issue by BLepers** [epfl-lara/stainless#66]
```scala
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._
import stainless.util.Random

object Scheduler {
   def test1(a:BigInt):Boolean = {
      ((x:BigInt) => a) == ((x:BigInt) => a)
   }.holds;

   case class B(x:BigInt=>BigInt);
   def test2(a:BigInt):Boolean = {
      val b = new B((x:BigInt) => a)
      ((x:BigInt) => a) == b.x
   }.holds;

   def test3(b:B) = {
      require(forall((e:BigInt) => b.x(e) == 0))
      val res = new B(_ => 0)
      res.x == b.x
   }.holds;

   def test4(b:B) = { // crash
      require(forall((e:BigInt) => b.x(e) == 0))
      ((x:BigInt) => 0) == b.x
   }.holds;

   def test5(a:BigInt):Boolean = { //crash
      require(a == 0)
      ((x:BigInt) => a) == ((x:BigInt) => 0)
   }.holds;
}
```

Weird behaviors and a crash:

* The warning says that == is always false on lambdas, but test1 hold:
```
[Warning ] ./bug3.scala:10:25: warning: comparing a fresh object using `==' will always yield false
                 ((x:BigInt) => a) == ((x:BigInt) => a)
[  Info  ] ║ test1     postcondition                    10:7       valid        nativez3       0.051    ║
```
* test1 and test2 hold, but not test3. I understand that in test1 and test2 the lambdas are exactly the same, but it seems a bit counter intuitive to me that they would hold while test3 wouldn't?

* test4 and test5 crash
```Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: inox.ast.TypeOps$TypeErrorException: Type error: ...```

**Comment by jad-hamza** [comment]
You can fix test4 and test5 crashing by changing `(x:BigInt) => 0)` to `(x:BigInt) => BigInt(0))`.
If the type of this lambda is inferred to be BigInt => Int, why doesn't the typing system fail nicely here?

The warning talks about equality using the Scala semantics (you can ignore it), which is different than
the Stainless/Inox equality semantics. Ideally this warning should be removed.

test3 and test4 fail because the current definition of lambda equality is some kind of "structural"
equality. I don't know the exact details, but I believe that with the current definition of equality, you
can never have f == ((x: BigInt) => [...]) when f is a free variable (or an argument variable).

For instance, even the following fails:
```   
   def test6(f: BigInt => BigInt):Boolean = { 
      f == ((x: BigInt) => f(x))
   } holds // fails
```

**Comment by BLepers** [comment]
Thanks for the explanations :)

**Comment by samarion** [comment]
You can have `f == ((x: BigInt) => ...)` in certain cases, but not if the lambda closes over `f` (or you could create recursive lambdas). For instance, test7 underneath is valid:
```scala
def test7(f: BigInt => BigInt): Boolean = {
  require(f == ((x: BigInt) => BigInt(0)))
  f(10) == 0
}.holds
```

As Jad said, equality is based on the structure to keep it computable, so lambdas having the same results doesn't imply they are equal (the reason why tests 3 and 4 fail).

I'm not sure why the error messages are so poor, I'll have to investigate.

**Comment by BLepers** [comment]
Yes, I understand the reason with test3 and test4 fail :) I actually was wondering if test1 and test2 should also fail. It seems that currently there is some kind of "structural" equality as Jad puts it, which is a bit unusual (i.e., it is not pointer equality nor result equality as one might expect). No big deal though :)

**Comment by jad-hamza** [comment]
But is it possible to prove that `f == ((x: BigInt) => ...)` for some [...], given an `f` which is unconstrained
(or constrained only by the values it returns).

**Comment by samarion** [comment]
Hmm, I don't think you can prove that, no.

**Comment by samarion** [comment]
The only remaining issue is due to equality of differently typed expressions, so I'll close this issue in favor of https://github.com/epfl-lara/stainless/issues/101
