### ISSUE TITLE
TypeCheckerSuite isn't run on larabot on master, it:test

### ISSUE THREAD

**Issue by Gorzen** [epfl-lara/stainless#673]
The bot doesn't seem to run the TypeCheckerSuite

http://laraquad4.epfl.ch:9000/epfl-lara/stainless/build/4265/24778

Only VerificationSuite is run, probably do to some extraction error. The bot starts running it but then stops.

**Comment by jad-hamza** [comment]
Thanks, I'm trying to refactor the benchmarks to take into account the `qed` type change in https://github.com/epfl-lara/stainless/pull/674
I also added an assertion to make sure there are no errors during extraction

**Comment by romac** [comment]
I just merged #674, does this mean we can close this issue?

**Comment by jad-hamza** [comment]
Yes, thanks!
