### ISSUE TITLE
Java version check fails for recent JDK versions (probably > 9?)

### ISSUE THREAD

**Issue by cgrigis** [epfl-lara/stainless#706]
```
$ ./frontends/scalac/target/universal/stage/bin/stainless-scalac 

The java installation you have is not up to date
requires at least version 1.6+, you have
version 11.0.4

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .

$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Debian-1deb10u1, mixed mode, sharing)
```
It looks like `java_version_check()` uses a lexicographic comparison:
```
(...)
  elif [[ ! "$java_version" > "1.6" ]]; then
(...)
```
Something like this? https://stackoverflow.com/questions/16989598/bash-comparing-version-numbers

**Comment by romac** [comment]
Fixed in b33528d7. Things should work as expected after you re-run `sbt universal:stage`.

**Comment by cgrigis** [comment]
> Things should work as expected after you re-run `sbt universal:stage`

Yes, all good, thank you. :)

**Comment by romac** [comment]
For anyone who stumbles upon this issue sometime:

Stainless should work fine on Java 11 (modulo some warnings about use of reflection due to ScalaZ3). It is however not compatible with Java 13 (but neither is sbt 1.3.0/Scala 2.13 if I am not mistaken).
