### ISSUE TITLE
Invalid overflow check? 

### ISSUE THREAD

**Issue by kushti** [epfl-lara/stainless#71]
This code:

```scala
def addManyLongs(amounts: Array[Long]): Long = {
    require(amounts.length > 1 && amounts.length < 10  &&
      forall((i: Int) => (i >= 0 && i < amounts.length) ==>
        (amounts(i) >= 0 && amounts(i) <= 1000)))

    var sum = 0L
    var i = 0

    (while (i < amounts.length) {
      sum = sum + amounts(i)
      i = i + 1
    }) invariant(i >= 0)

    sum
}.ensuring(_ >= 0)
```

fails overflow validation:

[  Info  ]  - Result for 'integer overflow' VC for addManyLongsWhile @63:13:
[Warning ]  => INVALID
[Warning ] Found counter-example:
[Warning ]   sum: Long            -> 9223372036854775553
[Warning ]   i: Int               -> 0
[Warning ]   amounts: Array[Long] -> Array(489, 489, 489, 489, 489, 489, 489, 489, 489)

Why such a counter-example is generated, if sum = 0 in the code?

**Comment by mantognini** [comment]
The problem is with the loop invariant. Some information is lost but also some is missing. E.g. `sum` should be bounded.

Here is a loop invariant that should work:

```
      }) invariant(
        i >= 0 && i <= amounts.length &&
        sum >= 0 && sum <= i * 1000
      )
```
