### ISSUE TITLE
Invalid measures inferred in RelationProcessor

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#725]
In #721, the RelationProcessor infers invalid measures for the following benchmarks:

- `termination/valid/ConstantPropagation`
- `termination/valid/HOTermination`
- `termination/valid/Indirect`
- `termination/valid/QuickSort`
- `verification/valid/MergeSort`
- `verification/valid/MergeSort2`

**Comment by rjraya** [comment]
How does one trace this?

- How do you know measure is given after RelationProcessor?
- Where do I have to look for the validity conditions?
