### ISSUE TITLE
ChainProcessor infers measure of the wrong type

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#726]
In #721, the ChainProcessor infers a measure of the wrong type for the following benchmarks, which triggers a runtime exception as it tries to call `tupleSelect` on values which are not tuples.

- `verification/valid/Nested14`
- `verification/valid/Nested16`

**Comment by jad-hamza** [comment]
Closed by https://github.com/epfl-lara/stainless/pull/967
