### ISSUE TITLE
Support for `return` (was: stainless crashes on code with returns)

### ISSUE THREAD

**Issue by saraswat** [epfl-lara/stainless#747]
Get an `stainless.frontend.package$UnsupportedCodeException: Could not extract return b (Scala tree of type class scala.reflect.internal.Trees$Return)`
on
```
object my_very_own_test {
    def my_max(a:BigInt, b:BigInt):BigInt = {
        if (a < b) return b
        a
    } ensuring { res => res == max(a, b)}
}
```
Would much appreciate if `return e` gets addressed in due course. Real code sometimes has complex return logic which can be simplified with the use of returns. (Something like a Sev 3 request.)

**Comment by romac** [comment]
`return` statements are currently not supported, but until then we should improve the error message.

**Comment by vkuncak** [comment]
Returns may actually be compiled to exceptions in `scalac`, so one might address this by doing the same transformation and supporting exceptions in Stainless.

**Comment by romac** [comment]
Didn't we have a student working on that at some point? Did they get anywhere with this?

**Comment by romac** [comment]
> It's just not clear how it would interact with imperative code elimination.

Yeah, one solution I remember looking into was to lift everything (ie. control flow + imperative features) into a reified continuation monad. Had some userland code that worked but never got around to implementing it.

**Comment by jad-hamza** [comment]
`return` is now (at least partially) supported! (but not exceptions or break)
https://epfl-lara.github.io/stainless/imperative.html?highlight=return#return-keyword
