### ISSUE TITLE
Invalid usage of BigInt.apply is missed by TreeSanitizer

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#755]
> Moved from https://github.com/epfl-lara/inox/issues/118

---

https://github.com/epfl-lara/inox/issues/118#issue-623712852 by @saraswat

Working with stainless to verify a heap sort. Let me know if you need to be able to reproduce this.

```
stainless  verified/src/main/scala/verified.scala --timeout=30 --debug=verification
[Warning ] Parallelism is disabled.
[Internal] Error: Lookup failed for function with symbol `apply$13`. Trace:
[Internal] - inox.ast.Definitions$AbstractSymbols.$anonfun$getFunction$1(Definitions.scala:197)
[Internal] - scala.Option.getOrElse(Option.scala:189)
[Internal] - inox.ast.Definitions$AbstractSymbols.getFunction(Definitions.scala:197)
[Internal] - inox.ast.Definitions$AbstractSymbols.getFunction$(Definitions.scala:196)
[Internal] - stainless.extraction.oo.ClassSymbols$ClassSymbols.getFunction(ClassSymbols.scala:18)
[Internal] - stainless.transformers.GhostTraverser.traverse(GhostTraverser.scala:53)
[Internal] - stainless.transformers.GhostTraverser.traverse$(GhostTraverser.scala:42)

(…snip…)
```

---

https://github.com/epfl-lara/inox/issues/118#issuecomment-633930666 by @saraswat

This can probably be reduced more, but I am out of time (the problem is I can trigger other bugs if I try to remove more code)...

```scala
import stainless._
import stainless.lang._
import stainless.collection._

sealed trait Tree
case object Leaf extends Tree
case class Node(
  value: BigInt,
  left: Tree,
  right: Tree,
  rank: BigInt
) extends Tree

object heap_sort {
    def merge(t1: Tree, t2: Tree): Tree = {
        Leaf
    } 

    def heapify(l: List[BigInt]):Tree = {
        l match {
          case Nil() => Leaf 
          case a::s => merge(Node(a, Leaf, Leaf, 1), heapify(s))
        }
    }  

    def sorted(l: List[BigInt]): Boolean = {
        l match {
          case Nil() => true
          case _ :: Nil() => true
          case a :: b :: s => a <= b && sorted(b ::s)
        }
    }

    def sort(t:Tree):List[BigInt] = {
        t match {
          case Leaf => Nil[BigInt]()
          case Node(k, l, r, _) => Cons(k, sort(merge(l,r)))
        }
        
    }
    def listSort(l:List[BigInt]): List[BigInt] = {
        sort(heapify(l))
    } ensuring (res => sorted(res))
 
    def num_in_list(x:BigInt, t:List[BigInt]): BigInt = {
        t match {
          case Nil() => BigInt(0)
          case a::s => BigInt(if (a == x) 1 else 0) + num_in_list(x, s)
        }
    } ensuring (res => res >= BigInt(0))
}
```

The culprit is likely `BigInt(if (a == x) 1 else 0)`. This is apparently not supposed to work. (Why? I do want it to work!) The funny thing is that if I test just this in isolation I get the right error message (no crash). Somehow in this larger context it is triggering a crash.

Comment out `num_in_list` and the crash will disappear.

**Comment by jad-hamza** [comment]
Thank you for the example! I'm having a look at the reporting issue.

In general `BigInt(some_int)` is not supported at the moment because this requires a general `intToBigInt` function. It's possible to write this function as a recursive function (maybe `intToBigInt(n+1) = intToBigInt(n) + 1`), but this might not work very well with automation. In this particular exemple you could pull the `if` out of the `BigInt`, would that also work for your original use case?

**Comment by jad-hamza** [comment]
(cc @saraswat)

**Comment by saraswat** [comment]
Thank you for checking. I have been able to work around all the issues I raised, and am good. This is a very exciting system. Thank you for all your good work. Looking forward to continued development.

**Comment by jad-hamza** [comment]
Can we close this as a duplicate of #667? (thanks @vkuncak for finding this issue)

**Comment by romac** [comment]
Closing as duplicate of #667
