### ISSUE TITLE
Traceback: What is special about StringBuilder...?

### ISSUE THREAD

**Issue by saraswat** [epfl-lara/stainless#770]
The following code works with stainless:
```
import stainless.annotation._
object verified {
  @extern def a(@extern sb: Any) = {}
}
```
But this code doesn't:

```
import stainless.annotation._
object verified {
  @extern def a(@extern sb: StringBuilder) = {}
}
```

What is special about `StringBuilder` (for stainless)...? Where did the `None.get` come from...? 

```
Compiling 31 Scala sources to /Users/savija/tmp/test/verified/target/scala-2.12/classes ...
[error] ## Exception when compiling 31 sources to /Users/savija/tmp/test/verified/target/scala-2.12/classes
[error] java.util.NoSuchElementException: None.get
[error] scala.None$.get(Option.scala:529)
[error] scala.None$.get(Option.scala:527)
[error] stainless.extraction.oo.Trees$TypeApply.getTypeDef(Trees.scala:155)
[error] stainless.extraction.oo.Trees$TypeApply.wellKinded(Trees.scala:145)
[error] stainless.extraction.oo.Trees$TypeApply.computeType(Trees.scala:139)
[error] stainless.extraction.oo.Trees$TypeApply.computeType(Trees.scala:137)
[error] inox.ast.Types$Type.getType(Types.scala:45)
[error] inox.ast.Definitions$VariableSymbol.getType(Definitions.scala:48)
[error] inox.ast.Definitions$VariableSymbol.getType$(Definitions.scala:48)
[error] inox.ast.Definitions$ValDef.getType(Definitions.scala:84)
[error] inox.ast.Types$Typed.isTyped(Types.scala:12)
[error] inox.ast.Types$Typed.isTyped$(Types.scala:12)
[error] inox.ast.Definitions$ValDef.isTyped(Definitions.scala:84)

```

**Comment by saraswat** [comment]
This might be  a good time to get some clarification: Which existing (Java, Scala) classes does stainless know about and which ones does it know about?

e..g. above I can use`java.lang.String` or `java.lang.StringBuilder`  or `StringBuffer` without any problem. 

But not `StringBuilder`.

**Comment by romac** [comment]
That seems like a bug, given the `None.get` exception, and the fact that Stainless shouldn't care about the types mentioned in an extern method signature.

Aside from that, there is no dedicated support for either of `java.lang.StringBuilder`, `java.lang.StringBuffer`, or `scala.collection.mutable.StringBuilder`.

In non-extern context, Stainless currently supports only a very small subset of the Scala standard library, and pretty much nothing from the Java one, aside from primitive types and `String`.

I unfortunately don't have a comprehensive list of every class supported by Stainless at hand, but that would indeed be a valuable addition to the documentation. Tracking this in #772.

**Comment by jad-hamza** [comment]
The crash is fixed in PR https://github.com/epfl-lara/stainless/pull/782/
But the program is still rejected because the type is not recognized by Inox.
Should we make something during extraction or an early phase to replace all unknown types by dummy placeholder types?

**Comment by romac** [comment]
We already have a [special phase](https://github.com/epfl-lara/stainless/blob/master/core/src/main/scala/stainless/frontend/Recovery.scala) after extraction that replaces unknown types in `@extern` with a placeholder type. So we could perhaps provide a configuration option which would run that recovery strategy on all definitions rather than just the `@extern` ones.
