### ISSUE TITLE
Incorrect handling of val initialization wrt. scalac semantics

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#799]
This program verifies:
```scala
object Test {
  case class Hello() {
    val message = answer + 3
    val answer = 42
  }
  def getM: Int = {
    new Hello().message
  } ensuring (_ == 45)
}
```
but in fact `message` access `answer` before it is initialized (scalac gives warning) and the value that `getM` returns is 3.

 `stainless-scalac Hello.scala --debug=trees` shows mapping to `def`, which is maybe conservative for `lazy val` but not `val`
```
[ Debug  ] @field
[ Debug  ] def message(thiss: Hello): Int = {
[ Debug  ]   assert(((answer(thiss) & -2147483648) == (3 & -2147483648)) ==> ((answer(thiss) & -2147483648) == (answer(thiss) + 3 & -2147483648)), "Addition overflow")
[ Debug  ]   answer(thiss) + 3
[ Debug  ] }
[ Debug  ] @private
[ Debug  ] @field
[ Debug  ] def answer(thiss: Hello): Int = 42
```

We may wish to disallow these `val`s inside classes and only allow `lazy val`s.

**Comment by vkuncak** [comment]
Note that translating everything to `def` on its own means that we do not trigger evaluation of anything. It seems to me that we would need to model constructor invocation as a function that is applied when ADT instance is created, so we know this computation happens. In such constructor we can create local `val`s in the declaration order that we then use to initialize ADT.

**Comment by samarion** [comment]
Yes, that's something I had thought of initially but this would significantly complicate verification because we'd be lugging around a bunch of extra constructor calls. I think we can have a reasonable middle ground with limited val overrides and forcing vals to only refer to previously defined vals (in the same class). This has the additional benefit that it forces users to stay in a sane (or at least san*er*) subset of Scala.

**Comment by vkuncak** [comment]
Ok, let us keep initializers sane as @samarion says. Keep in mind that currently this works as well, so we should prevent cases like this (which currently wrongly passes as well):
```scala
object Test {
  def m(t: Foo) = {
    t.g
  }
  case class Foo() {
    val f = m(this)
    val g = 42
  }
  def getF = {
    new Foo().f
  } ensuring (_ == 42)
}
```

**Comment by saraswat** [comment]
Initializers, constructors -- lots of insanity around. We went for a hard hat approach in X10. Basic ideas could probably be made to work in Scala. Though I agree forcing `val` to refer only to previously defined `val` is a sensible restriction. 

Is `lazy val` supported by Stainless?

**Comment by jad-hamza** [comment]
Yes I think this is extracted as a function `def` for verification.

**Comment by jad-hamza** [comment]
Closed by https://github.com/epfl-lara/stainless/pull/810
