### ISSUE TITLE
Clarify relationship with Leon for newbies

### ISSUE THREAD

**Issue by bbarker** [epfl-lara/stainless#8]
Hi,

I'm a newbie to Stainless and Leon - neither README for Stainless or Leon seems to mention the other, but the READMEs clearly have some relationship. I assume Stainless is the newer system, so it would be helpful if there was at least some explanation on a comparison between the two (features, reasons for divergence, maturity, etc).

Thanks!

**Comment by samarion** [comment]
Thanks for the remark, addressed in https://github.com/epfl-lara/stainless/pull/9
