### ISSUE TITLE
Error: could not check that Int0 is a subtype of Int when using induct annotation

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#803]
This code gives:
```
Could not check that Int0 is a subtype of Int
```
The error message is not helpful. How do we do induct on integers?

```scala
import stainless.lang._
import stainless.collection._
import stainless.annotation._
import stainless.lang.StaticChecks._
import scala.annotation._

object verified {

  @tailrec
  def countDown(n: Int): Int = {
    if (n > 0) countDown(n-1)
    else n
  }

  @induct
  def countDownNonneg(n: Int): Unit = {
    ()
  }.ensuring(_ => countDown(n) <= 0)
```
The same error is if the property is stated inside the body:
```scala
  @induct
  def countDownNonneg(n: Int): Boolean = {
    countDown(n) <= 0
  }.holds
```

**Comment by jad-hamza** [comment]
Thanks for the report! It should be fixed now, I had swapped the "size" and "value" field of the bitvectors in the `InductElimination` phase. The `Int0` type corresponds to bitvectors of size 0 (while I wanted a bitvector of size 32, with value 0).
