### ISSUE TITLE
Missfomed TIP source output?

### ISSUE THREAD

**Issue by mantognini** [epfl-lara/stainless#81]
When generating `.tip` files for debug, I've noticed that some of them don't parse in Inox. For example this one:

```
(declare-const i!20 (_ BitVec 32))

(declare-datatypes (A!251) ((array!160 (array!161 (arr!81 (Array (_ BitVec 32) A!251)) (size!120 (_ BitVec 32))))))

(define-fun foo!3 ((i!19 (_ BitVec 32))) (array!160 (_ BitVec 32)) (assume (bvsgt i!19 #b00000000000000000000000000000000) (let ((res!38 (array!161 ((as const (Array (_ BitVec 32) (_ BitVec 32))) #b00000000000000000000000000000000) i!19))) (assume (= (size!120 res!38) i!19) res!38))))

(datatype-invariant (par (A!250) array!141 (array!160 A!250) (bvsge (size!120 array!141) #b00000000000000000000000000000000)))

(assert (not (=> (bvsgt i!20 #b00000000000000000000000000000000) (let ((b!352 (foo!3 i!20))) (and (bvsge #b00000000000000000000000000000000 #b00000000000000000000000000000000) (bvslt #b00000000000000000000000000000000 (size!120 b!352)))))))

(check-sat)

; check-assumptions required here, but not part of tip standard
```

gives the following error:

```
[info] [Warning ] Failed to parse ../stainless/tip-sessions/AbstractRefinementMap.scala-65.tip: inox.tip.MissformedTIPException: Missfomed TIP source @?:?:
[info] [Warning ] could not instantiate List(TypeParameterDef(A!251)) in List(Map[Int, A!251], Int32Type) given List(Map[Map[Int, Int], Int], Int32Type)
```

Now, I don't know much about tip and the assumptions behind it so I don't know if this is a bug in:
  1. (hopefully unlikely) a bug in stainless internal representation of programs,
  1. stainless' TIP output,
  2. inox's TIP parser.

[Here](https://gist.github.com/mantognini/2d9532430ebb80ead943003fdc8215b4/archive/1d927647722cdc8d1f2f501824e27890fef33728.zip) is a zip archive of a bunch of tip files, some of them being rejected by inox.

**Comment by samarion** [comment]
This particular issue is due to a bug in the SMTLIB parsing of Inox here:
https://github.com/epfl-lara/inox/blob/f105308eb60913349911457b4aeaa0c5ff65d485/src/main/scala/inox/solvers/smtlib/SMTLIBParser.scala#L192
which should be something like
```scala
val ArrayType(from, to) = fromSMT(sort)
FiniteMap(Seq.empty, d, from, to)
```

**Comment by mantognini** [comment]
Okay! There's no `ArrayType` in inox, but `MapType` seems to work. Does that make sense to you?

**Comment by samarion** [comment]
Ah yes, sorry my bad. I indeed meant `MapType`.

**Comment by mantognini** [comment]
Alright. Looking into the other failing cases, then will open a PR. I think I've got it now.
