### ISSUE TITLE
bug in isMutableClassType leading to an infinite loop for immutable recursive class types

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#811]
Thanks to @samarion for diagnosing:
 
an infinite loop involving this code path:
 

[error] java.lang.StackOverflowError

[error] stainless.extraction.imperative.SymbolOps.$anonfun$isMutableClassType$1(SymbolOps.scala:62)

[error] stainless.extraction.imperative.SymbolOps.$anonfun$isMutableClassType$1$adapted(SymbolOps.scala:61)

[error] scala.collection.LinearSeqOptimized.exists(LinearSeqOptimized.scala:95)

[error] scala.collection.LinearSeqOptimized.exists$(LinearSeqOptimized.scala:92)

[error] scala.collection.immutable.List.exists(List.scala:89)

[error] stainless.extraction.imperative.SymbolOps.stainless$extraction$imperative$SymbolOps$$isMutableClassType(SymbolOps.scala:61)

[error] stainless.extraction.imperative.SymbolOps.isMutableType(SymbolOps.scala:78)

[error] stainless.extraction.imperative.SymbolOps.isRealMutableType(SymbolOps.scala:68)

[error] stainless.extraction.imperative.SymbolOps.$anonfun$isMutableClassType$1(SymbolOps.scala:62)

[error] stainless.extraction.imperative.SymbolOps.$anonfun$isMutableClassType$1$adapted(SymbolOps.scala:61)

[error] scala.collection.LinearSeqOptimized.exists(LinearSeqOptimized.scala:95)

[error] scala.collection.LinearSeqOptimized.exists$(LinearSeqOptimized.scala:92)

[error] scala.collection.immutable.List.exists(List.scala:89)

[error] stainless.extraction.imperative.SymbolOps.stainless$extraction$imperative$SymbolOps$$isMutableClassType
>  > Looks like an infinite loop involving this code path.
> 
> 
> Yes, there's a bug in isMutableClassType where it can enter an infinite 
> loop for immutable recursive class types: 
> https://github.com/epfl-lara/stainless/blob/2372c03de6e9cba91d267a9e63f1504718ea264e/core/src/main/scala/stainless/extraction/imperative/SymbolOps.scala#L62
>

**Comment by jad-hamza** [comment]
Fixed in #824
