### ISSUE TITLE
Forbid overriding abstract defs by non-field vals

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#816]
From @samarion:

> One other issue I've realized is that abstract defs shouldn't be overriden by (non-field) vals because you run into the same nullness problem. We should also add a check for that in the TreeSanitizer.

**Comment by jad-hamza** [comment]
This kind of override you mean?

```scala
object ValOverrideAbstract {
  sealed abstract class A {
    def f: BigInt
  }

  case class B() extends A {
    val f: BigInt = 0
  }
}
```

**Comment by samarion** [comment]
Yes, exactly. This program should be rejected.

**Comment by vkuncak** [comment]
@jad-hamza this should also not be too hard to check, right?

**Comment by vkuncak** [comment]
Also, when we implement a check, we should try to document it. We would like to have a more comprehensive Verified Scala language description.

**Comment by jad-hamza** [comment]
Oh I forgot to close this, the check was added in https://github.com/epfl-lara/stainless/pull/810, I'll add some documentation.
