### ISSUE TITLE
Strange reporting

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#838]
The combination of these two methods:
```scala
  def onlyBool: Boolean = {
    true
  } ensuring (_ => false)

  def done: Unit = {
    onlyBool
  } ensuring(_ => false)
```
gives a report like this:
```scala
done      body assertion: Postcondition failed @37:5  valid    nativez3  ?:?:?       
onlyBool  postcondition                               invalid  nativez3  ListExt.scala:33:5  
```
In my view, Scala should reject this because the body of `done` should be returning boolean. But, unlike ocaml it does not reject it. What is strange is the message ` Postcondition failed` followed by `valid`. In fact, the VC should be valid (`false => false`), but it
looks like something gets misinterpreted due to the non-sensical types. Maybe we should just reject `done` with type error.

**Comment by vkuncak** [comment]
A possibly related example:
```scala
import stainless.collection._
import stainless.lang._
import stainless.annotation._
object SubList { 
  def subList[T](l1: List[T], l2: List[T]): Boolean = (l1, l2) match {
    case (Nil(), _)                 => true
    case (_, Nil())                 => false
    case (Cons(x, xs), Cons(y, ys)) => (x == y && subList(xs, ys)) || subList(l1, ys)
  }
 
  def subListTail[T](l1: List[T], @induct l2: List[T]): Unit = {
    require(!l1.isEmpty && subList(l1, l2))
    (l1,l2) match {
      case (Cons(x, xs), Cons(y, ys)) => subList(l1, ys)
    }
  }.ensuring(_ =>
    subList(l1.tail, l2)
  )
}
```

**Comment by jad-hamza** [comment]
`done` is extracted as this:

```scala
[ Debug  ] def done: Unit = {
[ Debug  ]   {
[ Debug  ]     onlyBool
[ Debug  ]   } ensuring {
[ Debug  ]     (x$2: Boolean) => false
[ Debug  ]   }
[ Debug  ]   ()
[ Debug  ] }
```

I remember there was a discussion somewhere talking about what we should do in that case, but I can't find it and I don't remember the conclusion. I'm opening a PR to reject `ensuring` in this position, let's see if this breaks something.

**Comment by jad-hamza** [comment]
The `Postcondition failed` is the error message that we write in the assertion corresponding to `ensuring` inside bodies, I'll change the message. This is used in `AssertionInjector` apparently but I'm not sure why `ensuring` would be allowed inside function bodies there.
