### ISSUE TITLE
Wrong ensuring clause for map in stainless/lang/Set.scala

### ISSUE THREAD

**Issue by Zyfarok** [epfl-lara/stainless#881]
Here :
https://github.com/epfl-lara/stainless/blob/0ebb00139688b6214909b939dc7c932b41c99bf8/frontends/library/stainless/lang/Set.scala#L36-L40

Isn't the ensuring clause false if the function f is a non-injective function ?
Shouldn't the clause be like this instead :
```scala
forall((a: A) => (!set.contains(a) || res.contains(f(a))))
&& forall((b: B) => (!res.contains(b) || exists((a: A) =>
  set.contains(a) && f(a) == b
)))
```

**Comment by jad-hamza** [comment]
You're right, thanks!

Perhaps we should remove the quantified post-conditions altogether. (quantifiers are not so well supported with the current version of Stainless)
