### ISSUE TITLE
GenC: Static check of GenC requirements

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#899]
https://epfl-lara.github.io/stainless/genc.html#requirements mentions some compiler requirements, most of which are guaranteed by C99. It'd be nice if these requirements were enforced in the generated C file. This could be achieved by statically including this code snippet in the generated C code:

```
#include <limits.h>
#if (__STDC_VERSION__ < 199901L) || (CHAR_BIT != 8)
#error "Your compiler does not meet the minimum requirements of Scala/GenC. Please see"
#error "https://epfl-lara.github.io/stainless/genc.html#requirements for more details."
#endif
```

**Comment by jad-hamza** [comment]
Closed by #902, thanks!
