### ISSUE TITLE
GenC: Support the "library written in Scala" scenario

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#900]
It would be nice if GenC supported the library scenario better. We have a C application and would like to embed some algorithms written in Scala/Stainless. For this use case, the following features would be nice:

- [x] Generate C code for Scala programs without `main` and `_main` functions
- [x] There should be a new annotation attribute `@export`. Scala functions with this annotation should be compiled to C, even if they are never called from anywhere else.
- [x] C function prototypes of `@export`ed functions should be written to a header file.

**Comment by jad-hamza** [comment]
Closed by #902, thanks!
