### ISSUE TITLE
Add a swap operation to swap references to mutable elements

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#943]
@vkuncak suggested we add a swap operation to be able to move/shift array elements (when the elements are mutable) without creating aliasing

@samarion any thoughts?

**Comment by jad-hamza** [comment]
See PR https://github.com/epfl-lara/stainless/pull/946 for a draft implementation

**Comment by vkuncak** [comment]
We can close this, @jad-hamza ?

**Comment by jad-hamza** [comment]
Yes, thanks!
