### ISSUE TITLE
(Unsigned) integer types not yet documented

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#948]
Could the new integer types (e.g. int32) be documented here: https://epfl-lara.github.io/stainless/purescala.html#predefined-types ?

**Comment by deiruch** [comment]
Please describe the following operations :)

`    def widen [X <: BV[_ <: BVKind with Singleton]]: X = { ??? }`
`    def narrow[X <: BV[_ <: BVKind with Singleton]]: X = { ??? }`

**Comment by jad-hamza** [comment]
We now have a little bit of documentation here: https://epfl-lara.github.io/stainless/purescala.html#bitvectors
