### ISSUE TITLE
Extraction issue for implicit classes

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#95]
This program returns a fatal error

```scala
object ImplicitClass {
  case class Test()
  def zero(t: Test) = 0
  implicit class TestNotation(t: Test) {
    def z() = zero(t)
  }
}
```

The extracted program looks like this:
```
class Test
class BoolNotation

def zero(t: Test): Int = 0

@method(BoolNotation)
def z: Int = zero(this.t)

@inline
@implicit
def BoolNotation(t: Test): BoolNotation = BoolNotation(t)
```

The output error I get is:
```
zero(this.t) is of type <untyped>
  this.t is of type <untyped>
    this is of type BoolNotation because zero was instantiated with  with type (Test) => Int
[ Error  ] ImplicitClass.scala:8:15: Type error: zero(this.t), expected Int32Type, found <untyped>
               def z() = zero(t)
                         ^^^^^^^
[ Error  ] The extracted sub-program in not well formed.
[ Error  ] Symbols are:
[ Error  ] functions -> [BoolNotation, z, zero]
[ Error  ] classes   -> [
[ Error  ]   class Test
[ Error  ]   class BoolNotation
[ Error  ] ]
[ Fatal  ] Aborting from CallBackWithRegistry
[ Error  ] Rethrowing exception emitted from within the compiler: Aborting from CallBackWithRegistry
```

**Comment by samarion** [comment]
Try writing it as
```scala
implicit class TestNotation(val t: Test) { ... }
```

It should be possible to extract your version too but I took a loot at it at some point and it would not be trivial.

**Comment by jad-hamza** [comment]
Ah thanks, yes that works, I think you already told me in the past :)
Perhaps we should add an error message during extraction, I can have a look.

**Comment by mantognini** [comment]
Do we (want to) support "normal"  `class` (as opposed to `case` or `abstract`)? A solution would be to simply reject those, maybe as a temporary solution.

**Comment by samarion** [comment]
I believe we do want to support implicit classes. IIRC scala complains when you declare these as `case` so I believe we should support "normal" implicit classes. At some point, it could also be interesting to support normal classes, though I don't know how complicated that will be.

**Comment by mantognini** [comment]
oh, I didn't realise `implicit case class` wasn't legal...

**Comment by jad-hamza** [comment]
Should we reject all classes (implicit or not) that are not case classes for the moment? I guess that could break some benchmarks that already use implicit classes. Can we easily define a minimal class fragment that is currently supported?

**Comment by mantognini** [comment]
> I guess that could break some benchmarks that already use implicit classes.

We can always convert implicit class to case class with a "companion" implicit conversion function, so this is not really an issue, hopefully.

**Comment by samarion** [comment]
The scalac extraction now correctly complains about non-val parameters.
We'll see about adding these checks to dotty later.
