### ISSUE TITLE
Add support for `_root_` package syntax

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#958]
Scala uses `_root_` to mark the start of the namespace:
https://docs.scala-lang.org/style/naming-conventions.html#root

Stainless stumbles over it with the following error message: `_root_ cannot be imported`

**Comment by jad-hamza** [comment]
I think the error message comes from the Scala compiler (for instance it appears in https://github.com/scala/bug/issues/6217 and https://github.com/scala/bug/issues/9125)

Could you try running `scalac` on your example as shown here: https://epfl-lara.github.io/stainless/installation.html#running-code-with-stainless-dependencies
```
scalac -d ~/.scala_objects $(find /path/to/Stainless/frontends/library/stainless/ -name "*.scala") File1.scala ... File_n.scala
```

**Comment by deiruch** [comment]
My bad. You can't actually import things from the _root_ namespace directly in scala. Sorry :)
