### ISSUE TITLE
F-Bounded types do not typecheck

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#97]
The following snippet [fails to typecheck](https://gist.github.com/313bdb2c9aa0b8c6ac4a388d8eae1b69):

```scala
abstract class Foo[A] {
    def foo(that: A): A
}

case class Bar() extends Foo[Bar] { // <- F-Bound here
    def foo(that: Bar): Bar = Bar()
}
```

It seems that `unwrap` is instantiated with `<untyped>` at some point, but I can't seem to figure out why.

Any idea where to look more specifically, @samarion?

**Comment by samarion** [comment]
The issue seems to be somewhere in `MethodLifting`, but I don't have enough info here to debug more. The call to `fi.getType` at https://github.com/epfl-lara/stainless/blob/master/core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala#L855 is returning `Untyped`. If you change the end of the `MethodLifting.transform` function to
```
val finalSymbols = t.NoSymbols.withFunctions(functions).withClasses(classes)
for (fd <- finalSymbols.functions.values) {
  if (!finalSymbols.isSubtypeOf(fd.fullBody.getType(finalSymbols), fd.returnType)) {
    println(fd)
    println(finalSymbols.explainTyping(fd.fullBody)(PrinterOptions()))
  }
}
finalSymbols
```
and post the output, I can maybe help pinpoint it a little better.

**Comment by romac** [comment]
@samarion Thank you so much for taking the time to look into this!

Here's the output with changes above:

```scala
def foo[A](thiss: Foo[A], that: A): A = if (thiss.isInstanceOf[Bar]) {
  foo(thiss.asInstanceOf[Bar], that)
} else {
  <empty tree>[A]
}

if (thiss.isInstanceOf[Bar]) {
  foo(thiss.asInstanceOf[Bar], that)
} else {
  <empty tree>[A]
} is of type <untyped>
  thiss.isInstanceOf[Bar] is of type Boolean
    thiss is of type Foo[A]
  foo(thiss.asInstanceOf[Bar], that) is of type <untyped>
    thiss.asInstanceOf[Bar] is of type Bar
      thiss is of type Foo[A]
    that is of type A because foo was instantiated with  with type (Bar,Bar) => Bar
  <empty tree>[A] is of type A
```

Here's how the monomorphized version of `foo` that is called in `foo(thiss.asInstanceOf[Bar], that) is of type <untyped>` looks like:

```scala
def foo(thiss: Bar, that: Bar): Bar = Bar()
```

It looks like `that` should also be casted as `Bar` instead of being passed as-is, is that right?

**Comment by romac** [comment]
and `foo(thiss.asInstanceOf[Bar], that)` needs to be casted to `A`, right?

ie.
```scala
foo(thiss.asInstanceOf[Bar], that.asInstanceOf[Bar]).asInstanceOf[A]
```

**Comment by samarion** [comment]
Yes, that's what it seems like indeed.
The code [here](https://github.com/epfl-lara/stainless/blob/3e8aa4485761908531f49cab606806bc21f4a777/core/src/main/scala/stainless/extraction/oo/MethodLifting.scala#L154-L159) should be changed to unify the types when necessary.

**Comment by romac** [comment]
Thanks! Should I try to re-use TypeEncoding.unifyTypes for this purpose? I've started refactoring it so that it can be used both as a standalone phase or within another phase, do that make sense to you?

**Comment by samarion** [comment]
No, I don't think the use cases are the same. `TypeEncoding.unifyTypes` will wrap and unwrap specialized types into boxes when required, whereas `MethodLifting.unifyTypes` should just insert casts I believe. Also the conditions in `TypeEncoding.unifyTypes` don't really make sense in the context of method lifting, you'll have to write some different code for this I'm afraid.

**Comment by romac** [comment]
Alright, makes sense, thanks!

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/061ef43aa912f9293efe6b81cf8f186b78c29149
