### ISSUE TITLE
Broken links in documentation search results (404)

### ISSUE THREAD

**Issue by deiruch** [epfl-lara/stainless#987]
For example, searching for "uint8" on https://epfl-lara.github.io/stainless/ lists a single result, where the link is broken:

https://epfl-lara.github.io/stainless/search.html?q=uint8&check_keywords=yes&area=default:
![image](https://user-images.githubusercontent.com/4119188/114846885-6c957700-9ddd-11eb-9657-344c4d26c2be.png)

The broken link is https://epfl-lara.github.io/stainless/gencundefined?highlight=uint8. Somehow, a `undefined` slipped in there...

**Comment by jad-hamza** [comment]
This seems to be because of the theme or the sphinx configuration we're using, I found this issue which is similar: https://github.com/enthought/traits/issues/1046

The standard theme hasn't been updated since 2017, time to change?

**Comment by jad-hamza** [comment]
Fixed, thanks!
