### ISSUE TITLE
Exception related to blocks and the Object type

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#99]
This code causes the following exception: 
> Caused by: java.util.NoSuchElementException: key not found: class stainless.extraction.imperative.Trees$Block`

It looks like this is coming from the innerfuns transformations. Perhaps this block should have been eliminated in a previous phase, in the ImperativeCleanup. (?)

```scala
object SI_BlockException {
  def test(b: Boolean): Boolean = {
    b match {
      case false => ()
      case true => test(b); test(b)
    }
    true
  } 
}
```

**Comment by samarion** [comment]
I can't reproduce this with the latest version of Stainless.

**Comment by gsps** [comment]
I can :-)

```scala
import stainless.lang._
import stainless.proof._

object Foo {
  def foo(): Boolean = {
    true
  } holds {
    check(1 == 1)
    true
  }
}
```

**Comment by samarion** [comment]
Really fixed this time in https://github.com/epfl-lara/stainless/commit/9f6ce6ea6719c37d80331ddaf1672082b1c25056
