### ISSUE TITLE
Stack trace if decrease after val

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#992]
The recent RBT bolts benchmark rejects val that defines a value used inside decreases.
It no longer works on master with:
```
bolts/data-structures/trees$ ~/software/stainless/stainless-scalac RedBlackTree.scala StrictlyOrderedList.scala --solvers=smt-z3
```
I guess `val`s may be useful inside `requires`, but even if rejected, it should not be stack trace.

**Comment by jad-hamza** [comment]
Should be good now, thanks for the report
